param()

function Convert-ColumnLine([string]$line) {
    $line = $line -replace 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    $line = $line -replace 'BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    $line = $line -replace 'SMALLINT UNSIGNED', 'SMALLINT'
    $line = $line -replace 'BIGINT UNSIGNED', 'BIGINT'
    $line = $line -replace 'TINYINT\(1\)', 'BOOLEAN'
    $line = $line -replace '\bJSON\b', 'JSONB'
    $line = $line -replace 'LONGTEXT', 'TEXT'
    $line = $line -replace 'DATETIME\(6\)', 'TIMESTAMP(6)'
    $line = $line -replace 'CURRENT_TIMESTAMP\(6\)', 'CURRENT_TIMESTAMP'
    $line = $line -replace ' ON UPDATE CURRENT_TIMESTAMP', ''
    $line = $line -replace 'BOOLEAN NOT NULL DEFAULT 0', 'BOOLEAN NOT NULL DEFAULT FALSE'
    $line = $line -replace 'BOOLEAN NOT NULL DEFAULT 1', 'BOOLEAN NOT NULL DEFAULT TRUE'
    $line = $line -replace 'BOOLEAN NULL DEFAULT 0', 'BOOLEAN NULL DEFAULT FALSE'
    $line = $line -replace 'BOOLEAN NULL DEFAULT 1', 'BOOLEAN NULL DEFAULT TRUE'
    return $line
}

function Convert-MySqlMigration([string]$path) {
    $lines = Get-Content -LiteralPath $path
    $output = New-Object System.Collections.Generic.List[string]
    $i = 0
    while ($i -lt $lines.Count) {
        $line = $lines[$i]
        if ($line -match '^CREATE TABLE IF NOT EXISTS ([a-zA-Z0-9_]+) \($') {
            $table = $Matches[1]
            $defs = New-Object System.Collections.Generic.List[string]
            $indexes = New-Object System.Collections.Generic.List[string]
            $i++
            while ($i -lt $lines.Count) {
                $inner = $lines[$i].Trim()
                if ($inner -match '^\)') {
                    break
                }
                if ($inner -ne '') {
                    if ($inner.EndsWith(',')) {
                        $inner = $inner.Substring(0, $inner.Length - 1)
                    }
                    if ($inner -match '^UNIQUE KEY ([a-zA-Z0-9_]+) \((.+)\)$') {
                        $indexes.Add("CREATE UNIQUE INDEX IF NOT EXISTS $($Matches[1]) ON $table ($($Matches[2]));")
                    }
                    elseif ($inner -match '^KEY ([a-zA-Z0-9_]+) \((.+)\)$') {
                        $indexes.Add("CREATE INDEX IF NOT EXISTS $($Matches[1]) ON $table ($($Matches[2]));")
                    }
                    else {
                        $defs.Add((Convert-ColumnLine $inner))
                    }
                }
                $i++
            }
            $output.Add("CREATE TABLE IF NOT EXISTS $table (")
            for ($j = 0; $j -lt $defs.Count; $j++) {
                $suffix = if ($j -lt $defs.Count - 1) { ',' } else { '' }
                $output.Add("    $($defs[$j])$suffix")
            }
            $output.Add(');')
            foreach ($index in $indexes) {
                $output.Add($index)
            }
        }
        else {
            $output.Add($line)
        }
        $i++
    }

    $content = ($output -join [Environment]::NewLine)
    $content = $content -replace '\) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;', ');'
    Set-Content -LiteralPath $path -Value $content
}

$paths = @(
    'rust-port\\crates\\db\\migrations\\0001_core_identity_dispatch.sql',
    'rust-port\\crates\\db\\migrations\\0002_auth_rbac_scaffolding.sql',
    'rust-port\\crates\\db\\migrations\\0003_marketplace_tracking_scaffolding.sql',
    'rust-port\\crates\\db\\migrations\\0004_payments_tms_scaffolding.sql',
    'rust-port\\crates\\db\\migrations\\0005_chat_presence_read_receipts.sql'
)
foreach ($path in $paths) {
    Convert-MySqlMigration $path
}
