-- Draft baseline generated from the Laravel code paths on 2026-04-05.
-- This is a code-derived starting point for the Rust port, not a substitute for a live schema dump.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id SMALLINT NULL,
    dob DATE NULL,
    gender VARCHAR(32) NULL,
    phone_no VARCHAR(64) NULL,
    ucr_hcc_no VARCHAR(128) NULL,
    mc_cbsa_usdot_no VARCHAR(128) NULL,
    ssn_no VARCHAR(64) NULL,
    address TEXT NULL,
    nationality VARCHAR(128) NULL,
    company_name VARCHAR(255) NULL,
    registration_number VARCHAR(128) NULL,
    tax_id VARCHAR(128) NULL,
    country_of_incorporation VARCHAR(128) NULL,
    consent_sanctions_screening BOOLEAN NULL,
    politically_exposed_person BOOLEAN NULL,
    source_of_funds TEXT NULL,
    agree_aml_policies BOOLEAN NULL,
    gov_id_number VARCHAR(128) NULL,
    cdl_number VARCHAR(128) NULL,
    cdl_expiry DATE NULL,
    cdl_class VARCHAR(64) NULL,
    regulatory_country VARCHAR(128) NULL,
    usdot_number VARCHAR(128) NULL,
    mc_number VARCHAR(128) NULL,
    ntn VARCHAR(128) NULL,
    vat_number VARCHAR(128) NULL,
    insurance_expiry DATE NULL,
    coverage_limits VARCHAR(255) NULL,
    insurer_name VARCHAR(255) NULL,
    vehicle_reg VARCHAR(128) NULL,
    vehicle_make_model VARCHAR(255) NULL,
    vehicle_year VARCHAR(16) NULL,
    vehicle_type VARCHAR(64) NULL,
    load_capacity DECIMAL(12,2) NULL,
    company_address TEXT NULL,
    bank_account VARCHAR(255) NULL,
    criminal_declaration BOOLEAN NULL,
    terms_agreed BOOLEAN NULL,
    trade_name VARCHAR(255) NULL,
    incorporation_date DATE NULL,
    director_name VARCHAR(255) NULL,
    director_dob DATE NULL,
    ubo_name VARCHAR(255) NULL,
    ubo_dob DATE NULL,
    ubo_nationality VARCHAR(255) NULL,
    ubo_address TEXT NULL,
    fmc_license VARCHAR(128) NULL,
    nvocc_reg VARCHAR(128) NULL,
    surety_bond VARCHAR(128) NULL,
    customs_broker_license VARCHAR(128) NULL,
    iata_accreditation VARCHAR(128) NULL,
    eori_number VARCHAR(128) NULL,
    secp_reg VARCHAR(128) NULL,
    chamber_reg VARCHAR(128) NULL,
    policy_number VARCHAR(128) NULL,
    insurer_contact VARCHAR(255) NULL,
    transport_modes TEXT NULL,
    countries_served TEXT NULL,
    customs_brokerage BOOLEAN NULL,
    consolidation_services BOOLEAN NULL,
    warehousing BOOLEAN NULL,
    years_in_operation VARCHAR(64) NULL,
    annual_volume VARCHAR(128) NULL,
    monthly_transaction_volume VARCHAR(128) NULL,
    ofac_consent BOOLEAN NULL,
    otp VARCHAR(16) NULL,
    otp_expires_at TIMESTAMP(6) NULL,
    otp_resend_count INT NOT NULL DEFAULT 0,
    last_otp_resend_at TIMESTAMP(6) NULL,
    image VARCHAR(512) NULL,
    email_verified_at TIMESTAMP(6) NULL,
    status SMALLINT NOT NULL DEFAULT 4,
    approved_at TIMESTAMP(6) NULL,
    rejected_at TIMESTAMP(6) NULL,
    kyc_pending_at TIMESTAMP(6) NULL,
    stripe_connect_account_id VARCHAR(255) NULL,
    payouts_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    kyc_status VARCHAR(64) NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

CREATE TABLE IF NOT EXISTS user_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_name VARCHAR(255) NULL,
    company_address TEXT NULL,
    dot_number VARCHAR(128) NULL,
    mc_number VARCHAR(128) NULL,
    equipment_types TEXT NULL,
    business_entity_id VARCHAR(128) NULL,
    facility_address TEXT NULL,
    fulfillment_contact_info TEXT NULL,
    fmcsa_broker_license_no VARCHAR(128) NULL,
    mc_authority_number VARCHAR(128) NULL,
    freight_forwarder_license VARCHAR(128) NULL,
    customs_license VARCHAR(128) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_details_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_details_user_id ON user_details (user_id);

CREATE TABLE IF NOT EXISTS user_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    admin_id BIGINT NULL,
    status SMALLINT NOT NULL,
    remarks TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_history_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_history_admin_id FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_user_history_user_id ON user_history (user_id);
CREATE INDEX IF NOT EXISTS idx_user_history_admin_id ON user_history (admin_id);

CREATE TABLE IF NOT EXISTS kyc_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_type VARCHAR(32) NOT NULL DEFAULT 'standard',
    file_path VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NULL,
    mime_type VARCHAR(255) NULL,
    file_size BIGINT NULL,
    hash VARCHAR(255) NULL,
    hash_algorithm VARCHAR(64) NULL,
    mock_blockchain_tx VARCHAR(255) NULL,
    mock_blockchain_timestamp TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kyc_documents_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_kyc_documents_user_id ON kyc_documents (user_id);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    iso_code VARCHAR(8) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_countries_name ON countries (name);

CREATE TABLE IF NOT EXISTS cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cities_country_id FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cities_country_name ON cities (country_id, name);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city_id BIGINT NULL,
    country_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_locations_city_id FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
    CONSTRAINT fk_locations_country_id FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_locations_city_id ON locations (city_id);
CREATE INDEX IF NOT EXISTS idx_locations_country_id ON locations (country_id);

CREATE TABLE IF NOT EXISTS load_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_load_types_name ON load_types (name);

CREATE TABLE IF NOT EXISTS equipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_equipments_name ON equipments (name);

CREATE TABLE IF NOT EXISTS commodity_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_commodity_types_name ON commodity_types (name);

CREATE TABLE IF NOT EXISTS loads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_number VARCHAR(64) NULL,
    title VARCHAR(255) NOT NULL,
    user_id BIGINT NULL,
    load_type_id BIGINT NULL,
    equipment_id BIGINT NULL,
    commodity_type_id BIGINT NULL,
    weight_unit VARCHAR(32) NULL,
    weight DECIMAL(12,2) NULL,
    special_instructions TEXT NULL,
    is_hazardous BOOLEAN NOT NULL DEFAULT FALSE,
    is_temperature_controlled BOOLEAN NOT NULL DEFAULT FALSE,
    status SMALLINT NOT NULL DEFAULT 1,
    leg_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_loads_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_loads_load_type_id FOREIGN KEY (load_type_id) REFERENCES load_types(id) ON DELETE SET NULL,
    CONSTRAINT fk_loads_equipment_id FOREIGN KEY (equipment_id) REFERENCES equipments(id) ON DELETE SET NULL,
    CONSTRAINT fk_loads_commodity_type_id FOREIGN KEY (commodity_type_id) REFERENCES commodity_types(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_loads_load_number ON loads (load_number);
CREATE INDEX IF NOT EXISTS idx_loads_user_id ON loads (user_id);
CREATE INDEX IF NOT EXISTS idx_loads_status ON loads (status);

CREATE TABLE IF NOT EXISTS load_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_type VARCHAR(32) NOT NULL DEFAULT 'standard',
    file_path VARCHAR(512) NOT NULL,
    original_name VARCHAR(255) NULL,
    mime_type VARCHAR(255) NULL,
    file_size BIGINT NULL,
    hash VARCHAR(255) NULL,
    hash_algorithm VARCHAR(64) NULL,
    mock_blockchain_tx VARCHAR(255) NULL,
    mock_blockchain_timestamp TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_load_documents_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_load_documents_load_id ON load_documents (load_id);

CREATE TABLE IF NOT EXISTS load_status_master (
    id SMALLINT NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_load_status_master_slug ON load_status_master (slug);

CREATE TABLE IF NOT EXISTS load_legs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id BIGINT NOT NULL,
    leg_no INT NOT NULL,
    leg_code VARCHAR(64) NULL,
    pickup_location_id BIGINT NOT NULL,
    delivery_location_id BIGINT NOT NULL,
    pickup_date TIMESTAMP(6) NULL,
    delivery_date TIMESTAMP(6) NULL,
    bid_status VARCHAR(32) NULL,
    price DECIMAL(12,2) NULL,
    status_id SMALLINT NOT NULL DEFAULT 1,
    booked_carrier_id BIGINT NULL,
    booked_at TIMESTAMP(6) NULL,
    booked_amount DECIMAL(12,2) NULL,
    accepted_offer_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_load_legs_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_legs_pickup_location_id FOREIGN KEY (pickup_location_id) REFERENCES locations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_load_legs_delivery_location_id FOREIGN KEY (delivery_location_id) REFERENCES locations(id) ON DELETE RESTRICT,
    CONSTRAINT fk_load_legs_booked_carrier_id FOREIGN KEY (booked_carrier_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_load_legs_status_id FOREIGN KEY (status_id) REFERENCES load_status_master(id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_load_legs_load_leg_no ON load_legs (load_id, leg_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_load_legs_leg_code ON load_legs (leg_code);
CREATE INDEX IF NOT EXISTS idx_load_legs_status_id ON load_legs (status_id);
CREATE INDEX IF NOT EXISTS idx_load_legs_booked_carrier_id ON load_legs (booked_carrier_id);
CREATE INDEX IF NOT EXISTS idx_load_legs_pickup_location_id ON load_legs (pickup_location_id);
CREATE INDEX IF NOT EXISTS idx_load_legs_delivery_location_id ON load_legs (delivery_location_id);

CREATE TABLE IF NOT EXISTS load_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id BIGINT NOT NULL,
    admin_id BIGINT NULL,
    status SMALLINT NOT NULL,
    remarks TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_load_history_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_history_admin_id FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_load_history_load_id ON load_history (load_id);
CREATE INDEX IF NOT EXISTS idx_load_history_admin_id ON load_history (admin_id);

CREATE TABLE IF NOT EXISTS carrier_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    equipment_id TEXT NULL,
    load_type_id TEXT NULL,
    country_id TEXT NULL,
    city_id TEXT NULL,
    availability_days TEXT NULL,
    max_weight_capacity DECIMAL(12,2) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_preferences_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_preferences_user_id ON carrier_preferences (user_id);

CREATE TABLE IF NOT EXISTS offer_status_master (
    id SMALLINT NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    slug VARCHAR(64) NOT NULL,
    description TEXT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_terminal BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_offer_status_master_slug ON offer_status_master (slug);

CREATE TABLE IF NOT EXISTS offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_leg_id BIGINT NOT NULL,
    carrier_id BIGINT NOT NULL,
    conversation_id BIGINT NULL,
    amount DECIMAL(12,2) NOT NULL,
    status_id SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_offers_load_leg_id FOREIGN KEY (load_leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_offers_carrier_id FOREIGN KEY (carrier_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_offers_status_id FOREIGN KEY (status_id) REFERENCES offer_status_master(id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_offers_load_leg_id ON offers (load_leg_id);
CREATE INDEX IF NOT EXISTS idx_offers_carrier_id ON offers (carrier_id);
CREATE INDEX IF NOT EXISTS idx_offers_status_id ON offers (status_id);

ALTER TABLE load_legs
    ADD CONSTRAINT fk_load_legs_accepted_offer_id FOREIGN KEY (accepted_offer_id) REFERENCES offers(id) ON DELETE SET NULL;

INSERT INTO load_status_master (id, name, slug, description, sort_order, is_terminal)
VALUES
    (0, 'Draft', 'draft', 'Pre-release or hidden state observed in the Laravel app.', 0, FALSE),
    (1, 'New', 'new', 'Freshly created leg awaiting review and marketplace handling.', 1, FALSE),
    (2, 'Reviewed', 'reviewed', 'Observed intermediate approval state.', 2, FALSE),
    (3, 'Offer Ready', 'offer_ready', 'Observed pre-booking state before acceptance.', 3, FALSE),
    (4, 'Booked', 'booked', 'Carrier accepted and leg booked.', 4, FALSE),
    (5, 'Pickup Started', 'pickup_started', 'Carrier has started pickup workflow.', 5, FALSE),
    (6, 'At Pickup', 'at_pickup', 'Carrier arrived at pickup.', 6, FALSE),
    (7, 'In Transit', 'in_transit', 'Carrier departed pickup and is in transit.', 7, FALSE),
    (8, 'Escrow Funded', 'escrow_funded', 'Funding gate satisfied before pickup execution.', 8, FALSE),
    (9, 'At Delivery', 'at_delivery', 'Carrier arrived at delivery.', 9, FALSE),
    (10, 'Delivered', 'delivered', 'Leg delivery completed.', 10, TRUE),
    (11, 'Paid Out', 'paid_out', 'Financial closeout complete.', 11, TRUE)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    is_terminal = EXCLUDED.is_terminal;

INSERT INTO offer_status_master (id, name, slug, description, sort_order, is_terminal)
VALUES
    (0, 'Declined', 'declined', 'Offer was declined by the load owner or carrier.', 0, TRUE),
    (1, 'Pending', 'pending', 'Offer submitted and awaiting decision.', 1, FALSE),
    (3, 'Accepted', 'accepted', 'Offer accepted and used to book the leg.', 3, TRUE)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    is_terminal = EXCLUDED.is_terminal;



