-- Marketplace, chat, execution, and tracking scaffolding.
-- This intentionally uses load_leg_id on conversations to match runtime Laravel code,
-- even though the committed Laravel migration still references load_id.

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_leg_id BIGINT NOT NULL,
    shipper_id BIGINT NOT NULL,
    carrier_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conversations_load_leg_id FOREIGN KEY (load_leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversations_shipper_id FOREIGN KEY (shipper_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_conversations_carrier_id FOREIGN KEY (carrier_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_conversations_leg_carrier ON conversations (load_leg_id, carrier_id);
CREATE INDEX IF NOT EXISTS idx_conversations_shipper_id ON conversations (shipper_id);
CREATE INDEX IF NOT EXISTS idx_conversations_carrier_id ON conversations (carrier_id);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    body TEXT NULL,
    meta JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_conversation_id FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages (user_id);

CREATE TABLE IF NOT EXISTS leg_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    lat DECIMAL(10,7) NOT NULL,
    lng DECIMAL(10,7) NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leg_locations_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_leg_locations_leg_id_recorded_at ON leg_locations (leg_id, recorded_at);

CREATE TABLE IF NOT EXISTS leg_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leg_events_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_leg_events_leg_id ON leg_events (leg_id);
CREATE INDEX IF NOT EXISTS idx_leg_events_type ON leg_events (type);

CREATE TABLE IF NOT EXISTS leg_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    path VARCHAR(512) NOT NULL,
    meta JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leg_documents_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_leg_documents_leg_id ON leg_documents (leg_id);
CREATE INDEX IF NOT EXISTS idx_leg_documents_type ON leg_documents (type);
