-- Payments, Stripe webhook, and STLOADS/TMS scaffolding.
-- Rust baseline note: escrows.leg_id is modeled as BIGINT to match the current load_legs scaffold,
-- even though the legacy Laravel escrow migration used UUID. Verify against live MySQL before cutover.
-- Rust baseline note: reconciliation audit uses the singular table name stloads_reconciliation_log
-- because that is what the Laravel model and reconciliation code currently reference.

CREATE TABLE IF NOT EXISTS escrows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    payer_user_id BIGINT NOT NULL,
    payee_user_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    amount BIGINT NOT NULL,
    platform_fee BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'unfunded',
    transfer_group VARCHAR(191) NULL,
    payment_intent_id VARCHAR(191) NULL,
    charge_id VARCHAR(191) NULL,
    transfer_id VARCHAR(191) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_escrows_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_escrows_payer_user_id FOREIGN KEY (payer_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_escrows_payee_user_id FOREIGN KEY (payee_user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_escrows_leg_id ON escrows (leg_id);
CREATE INDEX IF NOT EXISTS idx_escrows_status ON escrows (status);
CREATE INDEX IF NOT EXISTS idx_escrows_payer_user_id ON escrows (payer_user_id);
CREATE INDEX IF NOT EXISTS idx_escrows_payee_user_id ON escrows (payee_user_id);

CREATE TABLE IF NOT EXISTS stloads_handoffs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tms_load_id VARCHAR(100) NOT NULL,
    tenant_id VARCHAR(100) NULL,
    external_handoff_id VARCHAR(100) NULL,
    load_id BIGINT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'queued',
    tms_status VARCHAR(50) NULL,
    tms_status_at TIMESTAMP(6) NULL,
    party_type VARCHAR(50) NULL,
    freight_mode VARCHAR(50) NULL,
    equipment_type VARCHAR(100) NULL,
    commodity_description VARCHAR(255) NULL,
    weight DECIMAL(12,2) NULL,
    weight_unit VARCHAR(10) NOT NULL DEFAULT 'lbs',
    piece_count INT NULL,
    temperature_data JSONB NULL,
    container_data JSONB NULL,
    securement_data JSONB NULL,
    is_hazardous BOOLEAN NOT NULL DEFAULT FALSE,
    pickup_city VARCHAR(100) NULL,
    pickup_state VARCHAR(50) NULL,
    pickup_zip VARCHAR(20) NULL,
    pickup_country VARCHAR(5) NOT NULL DEFAULT 'US',
    pickup_address TEXT NULL,
    pickup_window_start TIMESTAMP(6) NULL,
    pickup_window_end TIMESTAMP(6) NULL,
    pickup_instructions TEXT NULL,
    pickup_appointment_ref VARCHAR(100) NULL,
    dropoff_city VARCHAR(100) NULL,
    dropoff_state VARCHAR(50) NULL,
    dropoff_zip VARCHAR(20) NULL,
    dropoff_country VARCHAR(5) NOT NULL DEFAULT 'US',
    dropoff_address TEXT NULL,
    dropoff_window_start TIMESTAMP(6) NULL,
    dropoff_window_end TIMESTAMP(6) NULL,
    dropoff_instructions TEXT NULL,
    dropoff_appointment_ref VARCHAR(100) NULL,
    board_rate DECIMAL(12,2) NULL,
    rate_currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    accessorial_flags JSONB NULL,
    bid_type VARCHAR(20) NOT NULL DEFAULT 'open',
    quote_status VARCHAR(30) NULL,
    tender_posture VARCHAR(30) NULL,
    compliance_passed BOOLEAN NOT NULL DEFAULT FALSE,
    compliance_summary JSONB NULL,
    required_documents_status JSONB NULL,
    readiness VARCHAR(30) NOT NULL DEFAULT 'pending',
    pushed_by VARCHAR(100) NULL,
    push_reason VARCHAR(255) NULL,
    source_module VARCHAR(50) NULL,
    queued_at TIMESTAMP(6) NULL,
    published_at TIMESTAMP(6) NULL,
    withdrawn_at TIMESTAMP(6) NULL,
    closed_at TIMESTAMP(6) NULL,
    retry_count INT NOT NULL DEFAULT 0,
    last_push_result TEXT NULL,
    payload_version VARCHAR(20) NOT NULL DEFAULT '1.0',
    last_webhook_at TIMESTAMP(6) NULL,
    raw_payload JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_handoffs_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_handoffs_external_handoff_id ON stloads_handoffs (external_handoff_id);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_tms_load_id ON stloads_handoffs (tms_load_id);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_tenant_id ON stloads_handoffs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_status_created_at ON stloads_handoffs (status, created_at);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_tms_load_status ON stloads_handoffs (tms_load_id, status);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_tms_status_status ON stloads_handoffs (tms_status, status);

CREATE TABLE IF NOT EXISTS stloads_handoff_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handoff_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    performed_by VARCHAR(100) NULL,
    source_module VARCHAR(50) NULL,
    payload_snapshot TEXT NULL,
    result TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_handoff_events_handoff_id FOREIGN KEY (handoff_id) REFERENCES stloads_handoffs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stloads_handoff_events_handoff_event_type ON stloads_handoff_events (handoff_id, event_type);

CREATE TABLE IF NOT EXISTS stloads_external_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handoff_id BIGINT NOT NULL,
    ref_type VARCHAR(50) NOT NULL,
    ref_value VARCHAR(255) NOT NULL,
    ref_source VARCHAR(100) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_external_refs_handoff_id FOREIGN KEY (handoff_id) REFERENCES stloads_handoffs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stloads_external_refs_handoff_ref_type ON stloads_external_refs (handoff_id, ref_type);
CREATE INDEX IF NOT EXISTS idx_stloads_external_refs_ref_value ON stloads_external_refs (ref_value);

CREATE TABLE IF NOT EXISTS stloads_sync_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handoff_id BIGINT NULL,
    error_class VARCHAR(80) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'warning',
    title VARCHAR(255) NOT NULL,
    detail TEXT NULL,
    source_module VARCHAR(100) NULL,
    performed_by VARCHAR(255) NULL,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMP(6) NULL,
    resolved_by VARCHAR(255) NULL,
    resolution_note TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_sync_errors_handoff_id FOREIGN KEY (handoff_id) REFERENCES stloads_handoffs(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_stloads_sync_errors_error_class_resolved ON stloads_sync_errors (error_class, resolved);
CREATE INDEX IF NOT EXISTS idx_stloads_sync_errors_severity_resolved ON stloads_sync_errors (severity, resolved);
CREATE INDEX IF NOT EXISTS idx_stloads_sync_errors_handoff_id ON stloads_sync_errors (handoff_id);

CREATE TABLE IF NOT EXISTS stloads_reconciliation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    handoff_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    tms_status_from VARCHAR(50) NULL,
    tms_status_to VARCHAR(50) NULL,
    stloads_status_from VARCHAR(50) NULL,
    stloads_status_to VARCHAR(50) NULL,
    detail TEXT NULL,
    triggered_by VARCHAR(100) NULL,
    webhook_payload JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_reconciliation_log_handoff_id FOREIGN KEY (handoff_id) REFERENCES stloads_handoffs(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stloads_reconciliation_log_handoff_action ON stloads_reconciliation_log (handoff_id, action);
CREATE INDEX IF NOT EXISTS idx_stloads_reconciliation_log_created_at ON stloads_reconciliation_log (created_at);
