-- Enterprise tenant, organization, and STLoads board baseline.
-- Additive only: this migration must be safe for empty PostgreSQL and existing staging schemas.

CREATE TABLE IF NOT EXISTS tenants (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    subscription_tier VARCHAR(80) NULL,
    billing_customer_id VARCHAR(191) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenants_slug ON tenants (slug);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants (status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    legal_name VARCHAR(255) NOT NULL,
    dba_name VARCHAR(255) NULL,
    organization_type VARCHAR(80) NOT NULL,
    ein VARCHAR(64) NULL,
    mc_number VARCHAR(64) NULL,
    dot_number VARCHAR(64) NULL,
    scac VARCHAR(64) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
    kyc_status VARCHAR(60) NOT NULL DEFAULT 'not_started',
    primary_contact_user_id BIGINT NULL,
    billing_email VARCHAR(255) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_organizations_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_organizations_primary_contact_user_id FOREIGN KEY (primary_contact_user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_tenant_legal_name ON organizations (tenant_id, legal_name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_tenant_ein ON organizations (tenant_id, ein) WHERE ein IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_organizations_tenant_status ON organizations (tenant_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_organizations_type_status ON organizations (organization_type, status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS organization_branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    branch_code VARCHAR(80) NULL,
    address_line1 VARCHAR(255) NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(120) NULL,
    state_region VARCHAR(80) NULL,
    postal_code VARCHAR(32) NULL,
    country_code VARCHAR(8) NOT NULL DEFAULT 'US',
    phone VARCHAR(80) NULL,
    email VARCHAR(255) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_organization_branches_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_branches_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_branches_code ON organization_branches (tenant_id, organization_id, branch_code) WHERE branch_code IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_organization_branches_org ON organization_branches (tenant_id, organization_id) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_key VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    invited_by BIGINT NULL,
    invited_at TIMESTAMP(6) NULL,
    accepted_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_organization_memberships_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_memberships_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_memberships_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_memberships_invited_by FOREIGN KEY (invited_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_memberships_active_user ON organization_memberships (tenant_id, organization_id, user_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_organization_memberships_user ON organization_memberships (tenant_id, user_id, status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS tenant_external_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    external_system VARCHAR(80) NOT NULL,
    external_tenant_id VARCHAR(191) NOT NULL,
    external_account_id VARCHAR(191) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tenant_external_mappings_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_external_mappings_system_tenant ON tenant_external_mappings (external_system, external_tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_external_mappings_tenant ON tenant_external_mappings (tenant_id, external_system, status);

CREATE TABLE IF NOT EXISTS stloads_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NULL,
    source_system VARCHAR(80) NOT NULL DEFAULT 'stloads',
    source_load_id VARCHAR(191) NULL,
    source_leg_id VARCHAR(191) NULL,
    posting_number VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    freight_mode VARCHAR(80) NOT NULL DEFAULT 'road',
    equipment_type VARCHAR(120) NULL,
    commodity_description VARCHAR(255) NULL,
    weight DECIMAL(12,2) NULL,
    weight_unit VARCHAR(20) NOT NULL DEFAULT 'lbs',
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    visibility VARCHAR(40) NOT NULL DEFAULT 'private',
    release_gate VARCHAR(80) NULL,
    readiness VARCHAR(40) NOT NULL DEFAULT 'pending',
    is_hazardous BOOLEAN NOT NULL DEFAULT FALSE,
    is_temperature_controlled BOOLEAN NOT NULL DEFAULT FALSE,
    active_version BIGINT NULL,
    published_at TIMESTAMP(6) NULL,
    withdrawn_at TIMESTAMP(6) NULL,
    closed_at TIMESTAMP(6) NULL,
    canceled_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_stloads_postings_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_postings_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_stloads_postings_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_postings_tenant_posting_number ON stloads_postings (tenant_id, posting_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_postings_source ON stloads_postings (tenant_id, source_system, source_load_id, source_leg_id) WHERE source_load_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_stloads_postings_active_search ON stloads_postings (tenant_id, status, visibility, published_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_stloads_postings_org_status ON stloads_postings (tenant_id, organization_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_stloads_postings_readiness ON stloads_postings (tenant_id, readiness, updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS stloads_posting_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    change_reason VARCHAR(255) NULL,
    normalized_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload_hash VARCHAR(128) NOT NULL,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_posting_versions_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_versions_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_versions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_posting_versions_number ON stloads_posting_versions (tenant_id, posting_id, version_number);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_versions_hash ON stloads_posting_versions (tenant_id, payload_hash);

ALTER TABLE stloads_postings
    ADD CONSTRAINT fk_stloads_postings_active_version FOREIGN KEY (active_version) REFERENCES stloads_posting_versions(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS stloads_posting_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    stop_sequence INT NOT NULL,
    stop_type VARCHAR(40) NOT NULL,
    facility_name VARCHAR(255) NULL,
    address_line1 VARCHAR(255) NULL,
    address_line2 VARCHAR(255) NULL,
    city VARCHAR(120) NOT NULL,
    state_region VARCHAR(80) NULL,
    postal_code VARCHAR(32) NULL,
    country_code VARCHAR(8) NOT NULL DEFAULT 'US',
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    window_start TIMESTAMP(6) NULL,
    window_end TIMESTAMP(6) NULL,
    appointment_ref VARCHAR(100) NULL,
    instructions TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_posting_stops_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_stops_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_posting_stops_sequence ON stloads_posting_stops (tenant_id, posting_id, stop_sequence);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_stops_location ON stloads_posting_stops (tenant_id, city, state_region, country_code);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_stops_window ON stloads_posting_stops (tenant_id, window_start, window_end);

CREATE TABLE IF NOT EXISTS stloads_posting_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    rate_type VARCHAR(40) NOT NULL DEFAULT 'flat',
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    amount DECIMAL(12,2) NOT NULL,
    min_amount DECIMAL(12,2) NULL,
    max_amount DECIMAL(12,2) NULL,
    accessorial_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_book_now BOOLEAN NOT NULL DEFAULT FALSE,
    effective_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_posting_rates_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_rates_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_rates_posting ON stloads_posting_rates (tenant_id, posting_id, effective_at DESC);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_rates_book_now ON stloads_posting_rates (tenant_id, is_book_now, amount, expires_at);

CREATE TABLE IF NOT EXISTS stloads_posting_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    requirement_type VARCHAR(80) NOT NULL,
    requirement_key VARCHAR(120) NOT NULL,
    requirement_value JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_posting_requirements_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_requirements_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_posting_requirements_key ON stloads_posting_requirements (tenant_id, posting_id, requirement_type, requirement_key);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_requirements_required ON stloads_posting_requirements (tenant_id, requirement_type, is_required);

CREATE TABLE IF NOT EXISTS stloads_posting_visibility_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    rule_type VARCHAR(60) NOT NULL,
    target_type VARCHAR(60) NOT NULL,
    target_id VARCHAR(191) NULL,
    allow BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMP(6) NULL,
    ends_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_posting_visibility_rules_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_posting_visibility_rules_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_visibility_rules_active ON stloads_posting_visibility_rules (tenant_id, posting_id, rule_type, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS idx_stloads_posting_visibility_rules_target ON stloads_posting_visibility_rules (tenant_id, target_type, target_id);
