-- Enterprise marketplace, carrier, offer, tender, booking, and compliance baseline.

CREATE TABLE IF NOT EXISTS carrier_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NULL,
    user_id BIGINT NULL,
    display_name VARCHAR(255) NOT NULL,
    carrier_type VARCHAR(80) NOT NULL DEFAULT 'motor_carrier',
    dot_number VARCHAR(64) NULL,
    mc_number VARCHAR(64) NULL,
    insurance_status VARCHAR(60) NOT NULL DEFAULT 'unknown',
    authority_status VARCHAR(60) NOT NULL DEFAULT 'unknown',
    compliance_status VARCHAR(60) NOT NULL DEFAULT 'pending',
    risk_score DECIMAL(6,2) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_carrier_profiles_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_profiles_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_carrier_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_profiles_org ON carrier_profiles (tenant_id, organization_id) WHERE organization_id IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_profiles_user ON carrier_profiles (tenant_id, user_id) WHERE user_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_carrier_profiles_status ON carrier_profiles (tenant_id, status, compliance_status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_carrier_profiles_dot_mc ON carrier_profiles (tenant_id, dot_number, mc_number) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS carrier_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    equipment_type VARCHAR(120) NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    max_weight DECIMAL(12,2) NULL,
    weight_unit VARCHAR(20) NOT NULL DEFAULT 'lbs',
    temperature_min DECIMAL(8,2) NULL,
    temperature_max DECIMAL(8,2) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_equipment_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_equipment_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_equipment_type ON carrier_equipment (tenant_id, carrier_profile_id, equipment_type);
CREATE INDEX IF NOT EXISTS idx_carrier_equipment_search ON carrier_equipment (tenant_id, equipment_type, status);

CREATE TABLE IF NOT EXISTS carrier_lanes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    origin_city VARCHAR(120) NULL,
    origin_state VARCHAR(80) NULL,
    origin_country VARCHAR(8) NOT NULL DEFAULT 'US',
    destination_city VARCHAR(120) NULL,
    destination_state VARCHAR(80) NULL,
    destination_country VARCHAR(8) NOT NULL DEFAULT 'US',
    radius_miles INT NULL,
    priority SMALLINT NOT NULL DEFAULT 5,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_lanes_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_lanes_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_carrier_lanes_search ON carrier_lanes (tenant_id, origin_state, destination_state, status);
CREATE INDEX IF NOT EXISTS idx_carrier_lanes_carrier ON carrier_lanes (tenant_id, carrier_profile_id, priority);

CREATE TABLE IF NOT EXISTS carrier_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    available_from TIMESTAMP(6) NOT NULL,
    available_until TIMESTAMP(6) NULL,
    city VARCHAR(120) NULL,
    state_region VARCHAR(80) NULL,
    country_code VARCHAR(8) NOT NULL DEFAULT 'US',
    equipment_type VARCHAR(120) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'available',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_availability_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_availability_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_carrier_availability_active ON carrier_availability (tenant_id, status, available_from, available_until);
CREATE INDEX IF NOT EXISTS idx_carrier_availability_location ON carrier_availability (tenant_id, state_region, equipment_type, status);

CREATE TABLE IF NOT EXISTS carrier_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    organization_id BIGINT NULL,
    name VARCHAR(255) NOT NULL,
    group_type VARCHAR(80) NOT NULL DEFAULT 'private_network',
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_carrier_groups_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_groups_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_groups_name ON carrier_groups (tenant_id, name) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_carrier_groups_org ON carrier_groups (tenant_id, organization_id, status) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS carrier_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_group_id BIGINT NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_group_members_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_group_members_group_id FOREIGN KEY (carrier_group_id) REFERENCES carrier_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_group_members_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_group_members_profile ON carrier_group_members (tenant_id, carrier_group_id, carrier_profile_id);
CREATE INDEX IF NOT EXISTS idx_carrier_group_members_profile ON carrier_group_members (tenant_id, carrier_profile_id, status);

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS posting_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS carrier_profile_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS offer_type VARCHAR(40) NOT NULL DEFAULT 'spot',
    ADD COLUMN IF NOT EXISTS currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP(6) NULL,
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(191) NULL,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE offers
    ADD CONSTRAINT fk_offers_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_offers_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    ADD CONSTRAINT fk_offers_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_offers_tenant_idempotency ON offers (tenant_id, idempotency_key) WHERE tenant_id IS NOT NULL AND idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_offers_posting_pending ON offers (tenant_id, posting_id, status_id, created_at DESC) WHERE tenant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_offers_carrier_profile ON offers (tenant_id, carrier_profile_id, created_at DESC) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS offer_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    offer_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    terms JSONB NOT NULL DEFAULT '{}'::jsonb,
    payload_hash VARCHAR(128) NOT NULL,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_offer_versions_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_offer_versions_offer_id FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE,
    CONSTRAINT fk_offer_versions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_offer_versions_number ON offer_versions (tenant_id, offer_id, version_number);
CREATE INDEX IF NOT EXISTS idx_offer_versions_hash ON offer_versions (tenant_id, payload_hash);

CREATE TABLE IF NOT EXISTS counteroffers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    offer_id BIGINT NOT NULL,
    posting_id BIGINT NOT NULL,
    from_party_type VARCHAR(40) NOT NULL,
    to_party_type VARCHAR(40) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    message TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMP(6) NULL,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_counteroffers_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_counteroffers_offer_id FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE CASCADE,
    CONSTRAINT fk_counteroffers_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_counteroffers_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_counteroffers_offer_status ON counteroffers (tenant_id, offer_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_counteroffers_posting_status ON counteroffers (tenant_id, posting_id, status);

CREATE TABLE IF NOT EXISTS tenders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    tender_number VARCHAR(100) NOT NULL,
    tender_type VARCHAR(60) NOT NULL DEFAULT 'direct',
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    expires_at TIMESTAMP(6) NULL,
    accepted_at TIMESTAMP(6) NULL,
    declined_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tenders_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tenders_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_tenders_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tenders_number ON tenders (tenant_id, tender_number);
CREATE INDEX IF NOT EXISTS idx_tenders_posting_status ON tenders (tenant_id, posting_id, status);

CREATE TABLE IF NOT EXISTS tender_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    tender_id BIGINT NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    invite_status VARCHAR(40) NOT NULL DEFAULT 'sent',
    sent_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP(6) NULL,
    response_note TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tender_invites_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_tender_invites_tender_id FOREIGN KEY (tender_id) REFERENCES tenders(id) ON DELETE CASCADE,
    CONSTRAINT fk_tender_invites_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tender_invites_carrier ON tender_invites (tenant_id, tender_id, carrier_profile_id);
CREATE INDEX IF NOT EXISTS idx_tender_invites_status ON tender_invites (tenant_id, invite_status, sent_at DESC);

CREATE TABLE IF NOT EXISTS booking_awards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    offer_id BIGINT NULL,
    tender_id BIGINT NULL,
    carrier_profile_id BIGINT NOT NULL,
    award_number VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'awarded',
    awarded_amount DECIMAL(12,2) NULL,
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    awarded_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at TIMESTAMP(6) NULL,
    closed_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_awards_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_awards_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_awards_offer_id FOREIGN KEY (offer_id) REFERENCES offers(id) ON DELETE SET NULL,
    CONSTRAINT fk_booking_awards_tender_id FOREIGN KEY (tender_id) REFERENCES tenders(id) ON DELETE SET NULL,
    CONSTRAINT fk_booking_awards_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_awards_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_awards_number ON booking_awards (tenant_id, award_number);
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_awards_active_posting ON booking_awards (tenant_id, posting_id) WHERE status IN ('awarded', 'accepted', 'in_transit');
CREATE INDEX IF NOT EXISTS idx_booking_awards_carrier_status ON booking_awards (tenant_id, carrier_profile_id, status);

CREATE TABLE IF NOT EXISTS booking_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    locked_by VARCHAR(191) NOT NULL,
    lock_reason VARCHAR(191) NOT NULL,
    lock_token VARCHAR(191) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    released_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_locks_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_locks_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_locks_token ON booking_locks (tenant_id, lock_token);
CREATE INDEX IF NOT EXISTS idx_booking_locks_active ON booking_locks (tenant_id, posting_id, expires_at) WHERE released_at IS NULL;

CREATE TABLE IF NOT EXISTS cancellation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    booking_award_id BIGINT NULL,
    requested_by BIGINT NULL,
    request_source VARCHAR(80) NOT NULL DEFAULT 'stloads',
    reason_code VARCHAR(80) NOT NULL,
    reason_detail TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    resolved_by BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cancellation_requests_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cancellation_requests_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_cancellation_requests_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL,
    CONSTRAINT fk_cancellation_requests_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_cancellation_requests_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_cancellation_requests_pending ON cancellation_requests (tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cancellation_requests_posting ON cancellation_requests (tenant_id, posting_id, status);

CREATE TABLE IF NOT EXISTS compliance_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NULL,
    organization_id BIGINT NULL,
    document_type VARCHAR(100) NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    file_hash VARCHAR(128) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
    issued_at TIMESTAMP(6) NULL,
    expires_at TIMESTAMP(6) NULL,
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_compliance_documents_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_documents_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_documents_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_documents_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_compliance_documents_unresolved ON compliance_documents (tenant_id, status, created_at DESC) WHERE status IN ('pending_review', 'rejected', 'expired');
CREATE INDEX IF NOT EXISTS idx_compliance_documents_expiring ON compliance_documents (tenant_id, expires_at) WHERE expires_at IS NOT NULL AND status = 'approved';
CREATE INDEX IF NOT EXISTS idx_compliance_documents_carrier ON compliance_documents (tenant_id, carrier_profile_id, document_type);

CREATE TABLE IF NOT EXISTS compliance_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    rule_key VARCHAR(120) NOT NULL,
    applies_to VARCHAR(80) NOT NULL,
    requirement JSONB NOT NULL DEFAULT '{}'::jsonb,
    severity VARCHAR(40) NOT NULL DEFAULT 'blocker',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_compliance_rules_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_compliance_rules_key ON compliance_rules (tenant_id, rule_key);
CREATE INDEX IF NOT EXISTS idx_compliance_rules_active ON compliance_rules (tenant_id, applies_to, active);

CREATE TABLE IF NOT EXISTS carrier_compliance_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    score DECIMAL(6,2) NULL,
    blocker_count INT NOT NULL DEFAULT 0,
    warning_count INT NOT NULL DEFAULT 0,
    evaluated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6) NULL,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_carrier_compliance_status_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_compliance_status_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_carrier_compliance_status_profile ON carrier_compliance_status (tenant_id, carrier_profile_id);
CREATE INDEX IF NOT EXISTS idx_carrier_compliance_status_unresolved ON carrier_compliance_status (tenant_id, status, evaluated_at DESC) WHERE status <> 'approved';

CREATE TABLE IF NOT EXISTS eligibility_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    eligible BOOLEAN NOT NULL,
    result_code VARCHAR(80) NOT NULL,
    result_detail TEXT NULL,
    evaluated_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    evaluated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_eligibility_results_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_eligibility_results_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_eligibility_results_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_eligibility_results_pair ON eligibility_results (tenant_id, posting_id, carrier_profile_id);
CREATE INDEX IF NOT EXISTS idx_eligibility_results_failures ON eligibility_results (tenant_id, eligible, evaluated_at DESC) WHERE eligible = FALSE;

CREATE TABLE IF NOT EXISTS compliance_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    posting_id BIGINT NULL,
    override_key VARCHAR(120) NOT NULL,
    reason TEXT NOT NULL,
    expires_at TIMESTAMP(6) NULL,
    approved_by BIGINT NOT NULL,
    revoked_by BIGINT NULL,
    revoked_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_compliance_overrides_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_overrides_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_overrides_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE CASCADE,
    CONSTRAINT fk_compliance_overrides_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_compliance_overrides_revoked_by FOREIGN KEY (revoked_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_compliance_overrides_active ON compliance_overrides (tenant_id, carrier_profile_id, override_key, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS carrier_risk_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    flag_type VARCHAR(100) NOT NULL,
    severity VARCHAR(40) NOT NULL DEFAULT 'watch',
    title VARCHAR(255) NOT NULL,
    detail TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'open',
    source_system VARCHAR(80) NULL,
    resolved_by BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carrier_risk_flags_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_risk_flags_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_risk_flags_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_carrier_risk_flags_open ON carrier_risk_flags (tenant_id, severity, created_at DESC) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_carrier_risk_flags_carrier ON carrier_risk_flags (tenant_id, carrier_profile_id, status);
