-- Enterprise integration, document, settlement, and operations extensions.

CREATE TABLE IF NOT EXISTS atmp_inbound_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    event_id VARCHAR(191) NOT NULL,
    correlation_id VARCHAR(191) NOT NULL,
    idempotency_key VARCHAR(191) NOT NULL,
    contract_version VARCHAR(40) NOT NULL,
    action VARCHAR(80) NOT NULL,
    atmp_load_id VARCHAR(191) NULL,
    atmp_leg_id VARCHAR(191) NULL,
    payload_hash VARCHAR(128) NOT NULL,
    raw_payload JSONB NOT NULL,
    normalized_payload JSONB NULL,
    validation_status VARCHAR(40) NOT NULL DEFAULT 'received',
    validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
    processed_at TIMESTAMP(6) NULL,
    failed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atmp_inbound_events_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_atmp_inbound_events_event_id ON atmp_inbound_events (tenant_id, event_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_atmp_inbound_events_idempotency ON atmp_inbound_events (tenant_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_atmp_inbound_events_load ON atmp_inbound_events (tenant_id, atmp_load_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_atmp_inbound_events_validation ON atmp_inbound_events (tenant_id, validation_status, created_at DESC);

CREATE TABLE IF NOT EXISTS atmp_outbound_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    event_id VARCHAR(191) NOT NULL,
    correlation_id VARCHAR(191) NULL,
    event_type VARCHAR(80) NOT NULL,
    posting_id BIGINT NULL,
    booking_award_id BIGINT NULL,
    target_url VARCHAR(512) NULL,
    payload JSONB NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'queued',
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NULL,
    last_attempt_at TIMESTAMP(6) NULL,
    last_error TEXT NULL,
    sent_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atmp_outbound_events_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_atmp_outbound_events_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE SET NULL,
    CONSTRAINT fk_atmp_outbound_events_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_atmp_outbound_events_event_id ON atmp_outbound_events (tenant_id, event_id);
CREATE INDEX IF NOT EXISTS idx_atmp_outbound_events_retry ON atmp_outbound_events (tenant_id, status, next_attempt_at, attempt_count);
CREATE INDEX IF NOT EXISTS idx_atmp_outbound_events_posting ON atmp_outbound_events (tenant_id, posting_id, created_at DESC);

CREATE TABLE IF NOT EXISTS atmp_contract_payloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    inbound_event_id BIGINT NULL,
    outbound_event_id BIGINT NULL,
    contract_version VARCHAR(40) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atmp_contract_payloads_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_atmp_contract_payloads_inbound_event_id FOREIGN KEY (inbound_event_id) REFERENCES atmp_inbound_events(id) ON DELETE CASCADE,
    CONSTRAINT fk_atmp_contract_payloads_outbound_event_id FOREIGN KEY (outbound_event_id) REFERENCES atmp_outbound_events(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_atmp_contract_payloads_hash ON atmp_contract_payloads (tenant_id, payload_hash);
CREATE INDEX IF NOT EXISTS idx_atmp_contract_payloads_direction ON atmp_contract_payloads (tenant_id, direction, created_at DESC);

CREATE TABLE IF NOT EXISTS atmp_sync_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    inbound_event_id BIGINT NULL,
    outbound_event_id BIGINT NULL,
    posting_id BIGINT NULL,
    error_class VARCHAR(100) NOT NULL,
    severity VARCHAR(40) NOT NULL DEFAULT 'warning',
    message TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_by BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atmp_sync_errors_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_atmp_sync_errors_inbound_event_id FOREIGN KEY (inbound_event_id) REFERENCES atmp_inbound_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_atmp_sync_errors_outbound_event_id FOREIGN KEY (outbound_event_id) REFERENCES atmp_outbound_events(id) ON DELETE SET NULL,
    CONSTRAINT fk_atmp_sync_errors_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE SET NULL,
    CONSTRAINT fk_atmp_sync_errors_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_atmp_sync_errors_unresolved ON atmp_sync_errors (tenant_id, severity, created_at DESC) WHERE resolved = FALSE;
CREATE INDEX IF NOT EXISTS idx_atmp_sync_errors_retry_class ON atmp_sync_errors (tenant_id, error_class, resolved);

CREATE TABLE IF NOT EXISTS dead_letter_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NULL,
    source_queue VARCHAR(120) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload JSONB NOT NULL,
    error_message TEXT NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    parked_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMP(6) NULL,
    resolved_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dead_letter_events_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL,
    CONSTRAINT fk_dead_letter_events_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_dead_letter_events_unresolved ON dead_letter_events (tenant_id, source_queue, parked_at DESC) WHERE resolved = FALSE;

CREATE TABLE IF NOT EXISTS document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    document_scope VARCHAR(80) NOT NULL,
    document_scope_id VARCHAR(191) NOT NULL,
    version_number INT NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NULL,
    file_size BIGINT NULL,
    file_hash VARCHAR(128) NOT NULL,
    uploaded_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_versions_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_versions_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_document_versions_scope_version ON document_versions (tenant_id, document_scope, document_scope_id, version_number);
CREATE INDEX IF NOT EXISTS idx_document_versions_hash ON document_versions (tenant_id, file_hash);

CREATE TABLE IF NOT EXISTS document_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    document_version_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    review_note TEXT NULL,
    reviewed_by BIGINT NULL,
    reviewed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_reviews_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_reviews_document_version_id FOREIGN KEY (document_version_id) REFERENCES document_versions(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_reviews_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_document_reviews_pending ON document_reviews (tenant_id, status, created_at DESC) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS required_document_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    rule_key VARCHAR(120) NOT NULL,
    applies_to VARCHAR(80) NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    expires_after_days INT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_required_document_rules_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_required_document_rules_key ON required_document_rules (tenant_id, rule_key);
CREATE INDEX IF NOT EXISTS idx_required_document_rules_active ON required_document_rules (tenant_id, applies_to, active);

CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    booking_award_id BIGINT NULL,
    carrier_profile_id BIGINT NULL,
    settlement_number VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    deductions_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
    approved_by BIGINT NULL,
    approved_at TIMESTAMP(6) NULL,
    paid_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settlements_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_settlements_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL,
    CONSTRAINT fk_settlements_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE SET NULL,
    CONSTRAINT fk_settlements_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_settlements_number ON settlements (tenant_id, settlement_number);
CREATE INDEX IF NOT EXISTS idx_settlements_status ON settlements (tenant_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS settlement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    settlement_id BIGINT NOT NULL,
    line_type VARCHAR(80) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_settlement_lines_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_settlement_lines_settlement_id FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_settlement_lines_settlement ON settlement_lines (tenant_id, settlement_id, line_type);

CREATE TABLE IF NOT EXISTS accessorial_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    posting_id BIGINT NULL,
    booking_award_id BIGINT NULL,
    requested_by BIGINT NULL,
    accessorial_type VARCHAR(100) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(5) NOT NULL DEFAULT 'USD',
    status VARCHAR(40) NOT NULL DEFAULT 'pending',
    reason TEXT NULL,
    resolved_by BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accessorial_requests_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_accessorial_requests_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE SET NULL,
    CONSTRAINT fk_accessorial_requests_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL,
    CONSTRAINT fk_accessorial_requests_requested_by FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_accessorial_requests_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_accessorial_requests_pending ON accessorial_requests (tenant_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS payment_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    settlement_id BIGINT NULL,
    booking_award_id BIGINT NULL,
    hold_reason VARCHAR(120) NOT NULL,
    amount DECIMAL(12,2) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    released_by BIGINT NULL,
    released_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_holds_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_holds_settlement_id FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_holds_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_holds_released_by FOREIGN KEY (released_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_payment_holds_active ON payment_holds (tenant_id, status, created_at DESC) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS payment_disputes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    settlement_id BIGINT NULL,
    booking_award_id BIGINT NULL,
    dispute_type VARCHAR(100) NOT NULL,
    amount DECIMAL(12,2) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'open',
    opened_by BIGINT NULL,
    resolved_by BIGINT NULL,
    resolved_at TIMESTAMP(6) NULL,
    detail TEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_disputes_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_disputes_settlement_id FOREIGN KEY (settlement_id) REFERENCES settlements(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_disputes_booking_award_id FOREIGN KEY (booking_award_id) REFERENCES booking_awards(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_disputes_opened_by FOREIGN KEY (opened_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_disputes_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_payment_disputes_open ON payment_disputes (tenant_id, status, created_at DESC) WHERE status = 'open';

CREATE TABLE IF NOT EXISTS factoring_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NOT NULL,
    factoring_company_name VARCHAR(255) NOT NULL,
    notice_of_assignment_key VARCHAR(512) NULL,
    remittance_email VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
    verified_by BIGINT NULL,
    verified_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_factoring_profiles_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_factoring_profiles_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_factoring_profiles_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_factoring_profiles_carrier ON factoring_profiles (tenant_id, carrier_profile_id);
CREATE INDEX IF NOT EXISTS idx_factoring_profiles_status ON factoring_profiles (tenant_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS quickpay_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    carrier_profile_id BIGINT NULL,
    organization_id BIGINT NULL,
    term_name VARCHAR(120) NOT NULL,
    fee_percent DECIMAL(6,3) NOT NULL DEFAULT 0,
    days_to_pay INT NOT NULL DEFAULT 2,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quickpay_terms_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_quickpay_terms_carrier_profile_id FOREIGN KEY (carrier_profile_id) REFERENCES carrier_profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_quickpay_terms_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_quickpay_terms_active ON quickpay_terms (tenant_id, status, carrier_profile_id, organization_id);

ALTER TABLE stloads_handoffs
    ADD COLUMN IF NOT EXISTS posting_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS inbound_event_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(191) NULL,
    ADD COLUMN IF NOT EXISTS payload_hash VARCHAR(128) NULL;

ALTER TABLE stloads_handoffs
    ADD CONSTRAINT fk_stloads_handoffs_posting_id FOREIGN KEY (posting_id) REFERENCES stloads_postings(id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_stloads_handoffs_inbound_event_id FOREIGN KEY (inbound_event_id) REFERENCES atmp_inbound_events(id) ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_stloads_handoffs_tenant_idempotency ON stloads_handoffs (tenant_id, idempotency_key) WHERE tenant_id IS NOT NULL AND idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_posting ON stloads_handoffs (tenant_id, posting_id, status) WHERE posting_id IS NOT NULL;
