-- Organization and tenant foundation for enterprise isolation.

CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(128) NOT NULL,
    account_type VARCHAR(64) NOT NULL DEFAULT 'enterprise',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    billing_email VARCHAR(255) NULL,
    support_tier VARCHAR(64) NOT NULL DEFAULT 'standard',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS slug VARCHAR(128),
    ADD COLUMN IF NOT EXISTS account_type VARCHAR(64) DEFAULT 'enterprise',
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'active',
    ADD COLUMN IF NOT EXISTS billing_email VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS support_tier VARCHAR(64) DEFAULT 'standard',
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE organizations
SET
    name = COALESCE(NULLIF(name, ''), CONCAT('Organization ', id)),
    slug = COALESCE(NULLIF(slug, ''), CONCAT('organization-', id)),
    account_type = COALESCE(NULLIF(account_type, ''), 'enterprise'),
    status = COALESCE(NULLIF(status, ''), 'active'),
    support_tier = COALESCE(NULLIF(support_tier, ''), 'standard'),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP);

ALTER TABLE organizations
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN slug SET NOT NULL,
    ALTER COLUMN account_type SET NOT NULL,
    ALTER COLUMN account_type SET DEFAULT 'enterprise',
    ALTER COLUMN status SET NOT NULL,
    ALTER COLUMN status SET DEFAULT 'active',
    ALTER COLUMN support_tier SET NOT NULL,
    ALTER COLUMN support_tier SET DEFAULT 'standard',
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS uq_organizations_slug ON organizations (slug);
CREATE INDEX IF NOT EXISTS idx_organizations_status ON organizations (status);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'organizations'
          AND column_name = 'tenant_id'
    ) THEN
        INSERT INTO organizations (
            id,
            tenant_id,
            legal_name,
            organization_type,
            name,
            slug,
            account_type,
            status,
            support_tier,
            metadata,
            created_at,
            updated_at
        )
        VALUES (
            1,
            COALESCE((SELECT id FROM tenants ORDER BY id LIMIT 1), 'default'),
            'STLoads Default Organization',
            'platform_default',
            'STLoads Default Organization',
            'stloads-default',
            'platform_default',
            'active',
            'standard',
            '{}'::jsonb,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        )
        ON CONFLICT (id) DO NOTHING;
    ELSE
        INSERT INTO organizations (id, name, slug, account_type, status, support_tier, created_at, updated_at)
        VALUES (1, 'STLoads Default Organization', 'stloads-default', 'platform_default', 'active', 'standard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (id) DO NOTHING;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS organization_roles (
    key VARCHAR(64) PRIMARY KEY,
    label VARCHAR(128) NOT NULL,
    description TEXT NULL,
    privileged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE organization_roles
    ADD COLUMN IF NOT EXISTS label VARCHAR(128),
    ADD COLUMN IF NOT EXISTS description TEXT NULL,
    ADD COLUMN IF NOT EXISTS privileged BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE organization_roles
SET
    label = COALESCE(NULLIF(label, ''), key),
    privileged = COALESCE(privileged, FALSE),
    created_at = COALESCE(created_at, CURRENT_TIMESTAMP);

ALTER TABLE organization_roles
    ALTER COLUMN label SET NOT NULL,
    ALTER COLUMN privileged SET NOT NULL,
    ALTER COLUMN privileged SET DEFAULT FALSE,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

INSERT INTO organization_roles (key, label, description, privileged)
VALUES
    ('owner', 'Owner', 'Organization owner with administrative authority.', TRUE),
    ('admin', 'Admin', 'Organization administrator for users, settings, and operational controls.', TRUE),
    ('finance', 'Finance', 'Finance operator for payments, escrow, and billing workflows.', TRUE),
    ('operator', 'Operator', 'Operations user for load, execution, and TMS workflows.', FALSE),
    ('member', 'Member', 'Default organization member.', FALSE),
    ('auditor', 'Auditor', 'Read-only review and compliance user.', FALSE)
ON CONFLICT (key) DO NOTHING;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE loads
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE load_documents
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE kyc_documents
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE conversations
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE escrows
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE stloads_handoffs
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE stloads_sync_errors
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

ALTER TABLE stloads_reconciliation_log
    ADD COLUMN IF NOT EXISTS organization_id BIGINT NOT NULL DEFAULT 1;

UPDATE users SET organization_id = 1 WHERE organization_id IS NULL;
UPDATE loads SET organization_id = COALESCE((SELECT organization_id FROM users WHERE users.id = loads.user_id), 1);
UPDATE load_documents
SET organization_id = COALESCE((SELECT organization_id FROM loads WHERE loads.id = load_documents.load_id), 1);
UPDATE kyc_documents
SET organization_id = COALESCE((SELECT organization_id FROM users WHERE users.id = kyc_documents.user_id), 1);
UPDATE conversations
SET organization_id = COALESCE((SELECT organization_id FROM users WHERE users.id = conversations.shipper_id), 1);
UPDATE offers
SET organization_id = COALESCE((
    SELECT loads.organization_id
    FROM load_legs
    INNER JOIN loads ON loads.id = load_legs.load_id
    WHERE load_legs.id = offers.load_leg_id
), 1);
UPDATE escrows
SET organization_id = COALESCE((
    SELECT loads.organization_id
    FROM load_legs
    INNER JOIN loads ON loads.id = load_legs.load_id
    WHERE load_legs.id = escrows.leg_id
), 1);
UPDATE stloads_handoffs
SET organization_id = COALESCE((SELECT organization_id FROM loads WHERE loads.id = stloads_handoffs.load_id), 1);
UPDATE stloads_sync_errors
SET organization_id = COALESCE((
    SELECT organization_id FROM stloads_handoffs WHERE stloads_handoffs.id = stloads_sync_errors.handoff_id
), 1);
UPDATE stloads_reconciliation_log
SET organization_id = COALESCE((
    SELECT organization_id FROM stloads_handoffs WHERE stloads_handoffs.id = stloads_reconciliation_log.handoff_id
), 1);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_organization_id') THEN
        ALTER TABLE users
            ADD CONSTRAINT fk_users_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_loads_organization_id') THEN
        ALTER TABLE loads
            ADD CONSTRAINT fk_loads_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_load_documents_organization_id') THEN
        ALTER TABLE load_documents
            ADD CONSTRAINT fk_load_documents_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kyc_documents_organization_id') THEN
        ALTER TABLE kyc_documents
            ADD CONSTRAINT fk_kyc_documents_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_conversations_organization_id') THEN
        ALTER TABLE conversations
            ADD CONSTRAINT fk_conversations_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_offers_organization_id') THEN
        ALTER TABLE offers
            ADD CONSTRAINT fk_offers_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_escrows_organization_id') THEN
        ALTER TABLE escrows
            ADD CONSTRAINT fk_escrows_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_stloads_handoffs_organization_id') THEN
        ALTER TABLE stloads_handoffs
            ADD CONSTRAINT fk_stloads_handoffs_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_stloads_sync_errors_organization_id') THEN
        ALTER TABLE stloads_sync_errors
            ADD CONSTRAINT fk_stloads_sync_errors_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_stloads_reconciliation_log_organization_id') THEN
        ALTER TABLE stloads_reconciliation_log
            ADD CONSTRAINT fk_stloads_reconciliation_log_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_users_organization_id ON users (organization_id);
CREATE INDEX IF NOT EXISTS idx_loads_organization_id ON loads (organization_id);
CREATE INDEX IF NOT EXISTS idx_load_documents_organization_id ON load_documents (organization_id);
CREATE INDEX IF NOT EXISTS idx_kyc_documents_organization_id ON kyc_documents (organization_id);
CREATE INDEX IF NOT EXISTS idx_conversations_organization_id ON conversations (organization_id);
CREATE INDEX IF NOT EXISTS idx_offers_organization_id ON offers (organization_id);
CREATE INDEX IF NOT EXISTS idx_escrows_organization_id ON escrows (organization_id);
CREATE INDEX IF NOT EXISTS idx_stloads_handoffs_organization_id ON stloads_handoffs (organization_id);
CREATE INDEX IF NOT EXISTS idx_stloads_sync_errors_organization_id ON stloads_sync_errors (organization_id);
CREATE INDEX IF NOT EXISTS idx_stloads_reconciliation_log_organization_id ON stloads_reconciliation_log (organization_id);

CREATE TABLE IF NOT EXISTS organization_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_key VARCHAR(64) NOT NULL DEFAULT 'member',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    invited_by_user_id BIGINT NULL,
    joined_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organization_memberships_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_memberships_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_organization_memberships_role_key FOREIGN KEY (role_key) REFERENCES organization_roles(key) ON DELETE RESTRICT,
    CONSTRAINT fk_organization_memberships_invited_by_user_id FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_memberships_org_user
    ON organization_memberships (organization_id, user_id);
CREATE INDEX IF NOT EXISTS idx_organization_memberships_user_id
    ON organization_memberships (user_id);
CREATE INDEX IF NOT EXISTS idx_organization_memberships_role_key
    ON organization_memberships (role_key);

INSERT INTO organization_memberships (organization_id, user_id, role_key, status, joined_at, created_at, updated_at)
SELECT
    users.organization_id,
    users.id,
    CASE
        WHEN users.role_id = 1 THEN 'admin'
        ELSE 'member'
    END,
    'active',
    COALESCE(users.created_at, CURRENT_TIMESTAMP),
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM users
ON CONFLICT (organization_id, user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION stloads_default_org_role_for_user_role(role_id SMALLINT)
RETURNS VARCHAR(64)
LANGUAGE plpgsql
AS $$
BEGIN
    IF role_id = 1 THEN
        RETURN 'admin';
    END IF;
    RETURN 'member';
END;
$$;

CREATE OR REPLACE FUNCTION stloads_sync_default_organization_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO organization_memberships (organization_id, user_id, role_key, status, joined_at, created_at, updated_at)
    VALUES (
        NEW.organization_id,
        NEW.id,
        stloads_default_org_role_for_user_role(NEW.role_id),
        'active',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (organization_id, user_id) DO UPDATE SET
        role_key = EXCLUDED.role_key,
        status = 'active',
        updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_sync_default_organization_membership ON users;
CREATE TRIGGER trg_users_sync_default_organization_membership
AFTER INSERT OR UPDATE OF organization_id, role_id ON users
FOR EACH ROW
EXECUTE FUNCTION stloads_sync_default_organization_membership();
