-- Tenant RBAC and support impersonation audit.

CREATE TABLE IF NOT EXISTS support_impersonation_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    actor_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_support_impersonation_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_impersonation_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_impersonation_target_user_id FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_support_impersonation_actor
    ON support_impersonation_audits (tenant_id, actor_user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_impersonation_target
    ON support_impersonation_audits (tenant_id, target_user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_support_impersonation_active
    ON support_impersonation_audits (tenant_id, expires_at)
    WHERE ended_at IS NULL;

INSERT INTO permissions (name, guard_name, created_at, updated_at)
VALUES
    ('manage_posting_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_offer_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_booking_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_document_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_payment_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_compliance_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_admin_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('manage_integration_actions', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('support_impersonation', 'web', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (name, guard_name) DO UPDATE SET updated_at = EXCLUDED.updated_at;

INSERT INTO role_has_permissions (permission_id, role_id)
SELECT p.id, 1
FROM permissions p
WHERE p.name IN (
    'manage_posting_actions',
    'manage_offer_actions',
    'manage_booking_actions',
    'manage_document_actions',
    'manage_payment_actions',
    'manage_compliance_actions',
    'manage_admin_actions',
    'manage_integration_actions',
    'support_impersonation'
)
ON CONFLICT DO NOTHING;
