-- Carrier load-board saved searches and alert rules.

CREATE TABLE IF NOT EXISTS load_board_saved_searches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    filters JSONB NOT NULL DEFAULT '{}'::jsonb,
    alert_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_load_board_saved_searches_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_board_saved_searches_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_load_board_saved_search_user_name
    ON load_board_saved_searches (tenant_id, user_id, name)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_load_board_saved_searches_user
    ON load_board_saved_searches (tenant_id, user_id, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS load_board_alert_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    saved_search_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    channel VARCHAR(40) NOT NULL DEFAULT 'email',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_load_board_alert_rules_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_board_alert_rules_saved_search_id FOREIGN KEY (saved_search_id) REFERENCES load_board_saved_searches(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_board_alert_rules_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_load_board_alert_rules_channel
    ON load_board_alert_rules (tenant_id, saved_search_id, user_id, channel)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_load_board_alert_rules_active
    ON load_board_alert_rules (tenant_id, user_id, active, updated_at DESC)
    WHERE deleted_at IS NULL;
