-- Enterprise audit ledger and time-boxed break-glass sessions.

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NULL,
    organization_id BIGINT NULL,
    target_organization_id BIGINT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NULL,
    action VARCHAR(120) NOT NULL,
    reason TEXT NULL,
    ticket_ref VARCHAR(191) NULL,
    request_id VARCHAR(191) NULL,
    ip_address VARCHAR(100) NULL,
    user_agent TEXT NULL,
    source VARCHAR(100) NOT NULL DEFAULT 'rust-backend',
    metadata JSONB NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_events_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_events_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_events_target_organization_id FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_events_actor_created_at ON audit_events (actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_organization_created_at ON audit_events (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_target_organization_created_at ON audit_events (target_organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_entity ON audit_events (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_action_created_at ON audit_events (action, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_break_glass_sessions (
    id VARCHAR(64) PRIMARY KEY,
    actor_user_id BIGINT NOT NULL,
    actor_organization_id BIGINT NULL,
    target_organization_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    ticket_ref VARCHAR(191) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_break_glass_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_break_glass_actor_organization_id FOREIGN KEY (actor_organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_admin_break_glass_target_organization_id FOREIGN KEY (target_organization_id) REFERENCES organizations(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_break_glass_actor_target
    ON admin_break_glass_sessions (actor_user_id, target_organization_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_break_glass_target_created_at
    ON admin_break_glass_sessions (target_organization_id, created_at DESC);
