-- P13 document hardening: review state, malware state, immutable audit, and richer rule targeting.

ALTER TABLE load_documents
    ADD COLUMN IF NOT EXISTS review_status VARCHAR(40) NOT NULL DEFAULT 'pending_review',
    ADD COLUMN IF NOT EXISTS review_note TEXT NULL,
    ADD COLUMN IF NOT EXISTS reviewed_by_user_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP(6) NULL,
    ADD COLUMN IF NOT EXISTS malware_scan_status VARCHAR(40) NOT NULL DEFAULT 'pending_scan',
    ADD COLUMN IF NOT EXISTS malware_scan_note TEXT NULL,
    ADD COLUMN IF NOT EXISTS payment_ready_blocked BOOLEAN NOT NULL DEFAULT TRUE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_load_documents_reviewed_by_user_id'
    ) THEN
        ALTER TABLE load_documents
            ADD CONSTRAINT fk_load_documents_reviewed_by_user_id
            FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_load_documents_review_status
    ON load_documents (load_id, review_status, malware_scan_status, payment_ready_blocked);

ALTER TABLE required_document_rules
    ADD COLUMN IF NOT EXISTS customer_user_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS mode VARCHAR(80) NULL,
    ADD COLUMN IF NOT EXISTS load_status_id SMALLINT NULL,
    ADD COLUMN IF NOT EXISTS payment_phase VARCHAR(80) NULL,
    ADD COLUMN IF NOT EXISTS max_file_size_bytes BIGINT NULL,
    ADD COLUMN IF NOT EXISTS allowed_mime_types JSONB NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_required_document_rules_targeting
    ON required_document_rules (tenant_id, customer_user_id, mode, load_status_id, payment_phase, active);

CREATE TABLE IF NOT EXISTS document_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    document_scope VARCHAR(80) NOT NULL,
    document_scope_id VARCHAR(191) NOT NULL,
    document_version_id BIGINT NULL,
    event_type VARCHAR(80) NOT NULL,
    actor_user_id BIGINT NULL,
    event_note TEXT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_document_audit_events_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_document_audit_events_document_version_id FOREIGN KEY (document_version_id) REFERENCES document_versions(id) ON DELETE SET NULL,
    CONSTRAINT fk_document_audit_events_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_document_audit_events_scope
    ON document_audit_events (tenant_id, document_scope, document_scope_id, id DESC);
