-- Tenant-scoped support notes and issue timeline entries for safe customer assistance.

CREATE TABLE IF NOT EXISTS support_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    actor_user_id BIGINT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(100) NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'internal',
    ticket_ref VARCHAR(191) NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_support_notes_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_notes_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_support_notes_visibility CHECK (visibility IN ('internal', 'customer_visible'))
);

CREATE INDEX IF NOT EXISTS idx_support_notes_org_created_at
    ON support_notes (organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_support_notes_entity_created_at
    ON support_notes (entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_support_notes_ticket_ref_created_at
    ON support_notes (ticket_ref, created_at DESC)
    WHERE ticket_ref IS NOT NULL;
