-- P14 payment hardening: Stripe webhook idempotency and finance workflow indexes.

CREATE TABLE IF NOT EXISTS stripe_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'default',
    event_id VARCHAR(191) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payment_intent_id VARCHAR(191) NULL,
    stripe_account_id VARCHAR(191) NULL,
    leg_id BIGINT NULL,
    processed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_stripe_webhook_events_tenant_id FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_stripe_webhook_events_event_id ON stripe_webhook_events (tenant_id, event_id);
CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_payment_intent ON stripe_webhook_events (tenant_id, payment_intent_id, event_type);
CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_leg ON stripe_webhook_events (tenant_id, leg_id, processed_at DESC);

ALTER TABLE settlements
    ADD COLUMN IF NOT EXISTS leg_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS escrow_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS quickpay_term_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS factoring_profile_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS settlement_ready_at TIMESTAMP(6) NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_settlements_leg_id') THEN
        ALTER TABLE settlements
            ADD CONSTRAINT fk_settlements_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_settlements_escrow_id') THEN
        ALTER TABLE settlements
            ADD CONSTRAINT fk_settlements_escrow_id FOREIGN KEY (escrow_id) REFERENCES escrows(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_settlements_quickpay_term_id') THEN
        ALTER TABLE settlements
            ADD CONSTRAINT fk_settlements_quickpay_term_id FOREIGN KEY (quickpay_term_id) REFERENCES quickpay_terms(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_settlements_factoring_profile_id') THEN
        ALTER TABLE settlements
            ADD CONSTRAINT fk_settlements_factoring_profile_id FOREIGN KEY (factoring_profile_id) REFERENCES factoring_profiles(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_settlements_leg_escrow ON settlements (tenant_id, leg_id, escrow_id) WHERE leg_id IS NOT NULL AND escrow_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_settlements_ready ON settlements (tenant_id, status, settlement_ready_at DESC) WHERE status IN ('ready', 'approved', 'paid');

ALTER TABLE accessorial_requests ADD COLUMN IF NOT EXISTS leg_id BIGINT NULL;
ALTER TABLE payment_holds ADD COLUMN IF NOT EXISTS leg_id BIGINT NULL;
ALTER TABLE payment_disputes ADD COLUMN IF NOT EXISTS leg_id BIGINT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_accessorial_requests_leg_id') THEN
        ALTER TABLE accessorial_requests
            ADD CONSTRAINT fk_accessorial_requests_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_holds_leg_id') THEN
        ALTER TABLE payment_holds
            ADD CONSTRAINT fk_payment_holds_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_disputes_leg_id') THEN
        ALTER TABLE payment_disputes
            ADD CONSTRAINT fk_payment_disputes_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_accessorial_requests_booking ON accessorial_requests (tenant_id, booking_award_id, status);
CREATE INDEX IF NOT EXISTS idx_payment_holds_booking ON payment_holds (tenant_id, booking_award_id, status);
CREATE INDEX IF NOT EXISTS idx_payment_disputes_booking ON payment_disputes (tenant_id, booking_award_id, status);
CREATE INDEX IF NOT EXISTS idx_accessorial_requests_leg ON accessorial_requests (tenant_id, leg_id, status);
CREATE INDEX IF NOT EXISTS idx_payment_holds_leg ON payment_holds (tenant_id, leg_id, status);
CREATE INDEX IF NOT EXISTS idx_payment_disputes_leg ON payment_disputes (tenant_id, leg_id, status);
