-- Enterprise identity provider, domain routing, and SCIM provisioning foundation.

CREATE TABLE IF NOT EXISTS organization_domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    domain VARCHAR(255) NOT NULL,
    verification_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    verification_token VARCHAR(128) NOT NULL,
    verified_at TIMESTAMP NULL,
    login_routing_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organization_domains_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT chk_organization_domains_verification_status CHECK (verification_status IN ('pending', 'verified', 'rejected'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_domains_domain
    ON organization_domains (LOWER(domain));
CREATE INDEX IF NOT EXISTS idx_organization_domains_organization_id
    ON organization_domains (organization_id);
CREATE INDEX IF NOT EXISTS idx_organization_domains_login_routing
    ON organization_domains (login_routing_enabled, verification_status);

CREATE TABLE IF NOT EXISTS enterprise_identity_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    provider_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    display_name VARCHAR(255) NOT NULL,
    issuer TEXT NULL,
    sso_url TEXT NULL,
    jwks_url TEXT NULL,
    metadata_url TEXT NULL,
    client_id TEXT NULL,
    jit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    default_role_key VARCHAR(64) NOT NULL DEFAULT 'member',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_enterprise_identity_providers_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_enterprise_identity_providers_default_role_key FOREIGN KEY (default_role_key) REFERENCES organization_roles(key) ON DELETE RESTRICT,
    CONSTRAINT chk_enterprise_identity_providers_type CHECK (provider_type IN ('oidc', 'saml')),
    CONSTRAINT chk_enterprise_identity_providers_status CHECK (status IN ('draft', 'active', 'disabled'))
);

CREATE INDEX IF NOT EXISTS idx_enterprise_identity_providers_org_status
    ON enterprise_identity_providers (organization_id, status);

CREATE TABLE IF NOT EXISTS scim_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    token_prefix VARCHAR(64) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    label VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    CONSTRAINT fk_scim_tokens_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT chk_scim_tokens_status CHECK (status IN ('active', 'revoked'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_scim_tokens_prefix
    ON scim_tokens (token_prefix);
CREATE INDEX IF NOT EXISTS idx_scim_tokens_organization_id
    ON scim_tokens (organization_id);

CREATE TABLE IF NOT EXISTS scim_user_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deprovisioned_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scim_user_links_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_scim_user_links_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_scim_user_links_org_external
    ON scim_user_links (organization_id, external_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_scim_user_links_org_user
    ON scim_user_links (organization_id, user_id);

CREATE TABLE IF NOT EXISTS scim_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    external_id VARCHAR(255) NULL,
    user_id BIGINT NULL,
    action VARCHAR(64) NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    reason TEXT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scim_events_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_scim_events_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_scim_events_outcome CHECK (outcome IN ('accepted', 'rejected', 'noop'))
);

CREATE INDEX IF NOT EXISTS idx_scim_events_org_created_at
    ON scim_events (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_scim_events_user_id
    ON scim_events (user_id);
