-- Enterprise least-privilege access reviews and recertification evidence.

CREATE TABLE IF NOT EXISTS access_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    title VARCHAR(191) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    review_type VARCHAR(64) NOT NULL DEFAULT 'quarterly',
    period_start TIMESTAMP NULL,
    period_end TIMESTAMP NULL,
    due_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_reviews_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_reviews_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_access_reviews_organization_status
    ON access_reviews (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_access_reviews_due_at
    ON access_reviews (due_at);

CREATE TABLE IF NOT EXISTS access_review_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    role_key VARCHAR(64) NOT NULL,
    role_label VARCHAR(128) NOT NULL,
    account_status SMALLINT NOT NULL,
    membership_status VARCHAR(32) NULL,
    last_activity_at TIMESTAMP NULL,
    risk_flags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    decision VARCHAR(32) NOT NULL DEFAULT 'pending',
    decision_reason TEXT NULL,
    decided_by_user_id BIGINT NULL,
    decided_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_review_items_review_id FOREIGN KEY (review_id) REFERENCES access_reviews(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_review_items_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_review_items_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_review_items_decided_by_user_id FOREIGN KEY (decided_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_access_review_items_review_user_role
    ON access_review_items (review_id, user_id, role_key);
CREATE INDEX IF NOT EXISTS idx_access_review_items_review_decision
    ON access_review_items (review_id, decision);
CREATE INDEX IF NOT EXISTS idx_access_review_items_user
    ON access_review_items (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS access_elevation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    current_role_key VARCHAR(64) NULL,
    requested_role_key VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    business_justification TEXT NOT NULL,
    decision_reason TEXT NULL,
    decided_by_user_id BIGINT NULL,
    decided_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_access_elevation_requests_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_elevation_requests_requester_user_id FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_elevation_requests_target_user_id FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_access_elevation_requests_decided_by_user_id FOREIGN KEY (decided_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_access_elevation_requests_org_status
    ON access_elevation_requests (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_access_elevation_requests_target
    ON access_elevation_requests (target_user_id, created_at DESC);
