CREATE TABLE IF NOT EXISTS customer_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    customer_user_id BIGINT NULL,
    contract_number VARCHAR(128) NOT NULL,
    contract_name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    effective_start DATE NOT NULL,
    effective_end DATE NULL,
    default_currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    service_rules JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_customer_contracts_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_contracts_customer_user_id FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_customer_contracts_status CHECK (status IN ('draft', 'active', 'suspended', 'expired', 'archived'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_contracts_org_number
    ON customer_contracts (organization_id, contract_number)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_customer_contracts_customer_status
    ON customer_contracts (organization_id, customer_user_id, status, effective_start, effective_end)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS customer_contract_lanes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    contract_id BIGINT NOT NULL,
    lane_name VARCHAR(255) NOT NULL,
    origin_location_id BIGINT NULL,
    destination_location_id BIGINT NULL,
    equipment_id BIGINT NULL,
    commodity_type_id BIGINT NULL,
    freight_mode VARCHAR(32) NOT NULL DEFAULT 'FTL',
    contracted_rate DECIMAL(12,2) NOT NULL,
    rate_currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    fuel_rule_key VARCHAR(128) NULL,
    accessorial_rules JSONB NULL,
    service_level VARCHAR(64) NULL,
    posting_behavior VARCHAR(32) NOT NULL DEFAULT 'contract',
    tender_priority INT NOT NULL DEFAULT 100,
    effective_start DATE NOT NULL,
    effective_end DATE NULL,
    service_rules JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_customer_contract_lanes_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_contract_lanes_contract_id FOREIGN KEY (contract_id) REFERENCES customer_contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_contract_lanes_origin_location_id FOREIGN KEY (origin_location_id) REFERENCES locations(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_contract_lanes_destination_location_id FOREIGN KEY (destination_location_id) REFERENCES locations(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_contract_lanes_equipment_id FOREIGN KEY (equipment_id) REFERENCES equipments(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_contract_lanes_commodity_type_id FOREIGN KEY (commodity_type_id) REFERENCES commodity_types(id) ON DELETE SET NULL,
    CONSTRAINT chk_customer_contract_lanes_posting_behavior CHECK (posting_behavior IN ('public', 'private', 'contract', 'internal'))
);

CREATE INDEX IF NOT EXISTS idx_customer_contract_lanes_contract
    ON customer_contract_lanes (contract_id, posting_behavior, effective_start, effective_end)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_customer_contract_lanes_lane_match
    ON customer_contract_lanes (organization_id, origin_location_id, destination_location_id, equipment_id, commodity_type_id, freight_mode)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS customer_lane_carriers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    lane_id BIGINT NOT NULL,
    carrier_user_id BIGINT NOT NULL,
    carrier_rank INT NOT NULL DEFAULT 1,
    carrier_role VARCHAR(32) NOT NULL DEFAULT 'preferred',
    rate_override DECIMAL(12,2) NULL,
    currency VARCHAR(8) NULL,
    service_rules JSONB NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_customer_lane_carriers_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_lane_carriers_lane_id FOREIGN KEY (lane_id) REFERENCES customer_contract_lanes(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_lane_carriers_carrier_user_id FOREIGN KEY (carrier_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_customer_lane_carriers_role CHECK (carrier_role IN ('preferred', 'backup'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_lane_carriers_rank
    ON customer_lane_carriers (lane_id, carrier_role, carrier_rank, carrier_user_id)
    WHERE deleted_at IS NULL;

ALTER TABLE loads
    ADD COLUMN IF NOT EXISTS customer_contract_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS customer_contract_lane_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS contract_rate DECIMAL(12,2) NULL,
    ADD COLUMN IF NOT EXISTS contract_rate_currency VARCHAR(8) NULL,
    ADD COLUMN IF NOT EXISTS contract_posting_behavior VARCHAR(32) NULL,
    ADD COLUMN IF NOT EXISTS contract_service_rules JSONB NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_loads_customer_contract_id'
    ) THEN
        ALTER TABLE loads
            ADD CONSTRAINT fk_loads_customer_contract_id
            FOREIGN KEY (customer_contract_id) REFERENCES customer_contracts(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_loads_customer_contract_lane_id'
    ) THEN
        ALTER TABLE loads
            ADD CONSTRAINT fk_loads_customer_contract_lane_id
            FOREIGN KEY (customer_contract_lane_id) REFERENCES customer_contract_lanes(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_loads_contract_posting_behavior'
    ) THEN
        ALTER TABLE loads
            ADD CONSTRAINT chk_loads_contract_posting_behavior
            CHECK (contract_posting_behavior IS NULL OR contract_posting_behavior IN ('public', 'private', 'contract', 'internal'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_loads_customer_contract_lane
    ON loads (organization_id, customer_contract_id, customer_contract_lane_id)
    WHERE deleted_at IS NULL;
