CREATE TABLE IF NOT EXISTS load_board_saved_filters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL DEFAULT 1,
    user_id BIGINT NULL,
    role_key VARCHAR(64) NULL,
    name VARCHAR(255) NOT NULL,
    filter_payload JSONB NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_load_board_saved_filters_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
    CONSTRAINT fk_load_board_saved_filters_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_load_board_saved_filters_user_name
    ON load_board_saved_filters (organization_id, user_id, LOWER(name))
    WHERE deleted_at IS NULL AND user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_load_board_saved_filters_role
    ON load_board_saved_filters (organization_id, role_key, is_default)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_load_board_search_pickup_date
    ON load_legs (pickup_date, status_id, booked_carrier_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_load_board_search_delivery_date
    ON load_legs (delivery_date, status_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_load_board_search_price
    ON load_legs (price)
    WHERE deleted_at IS NULL AND price IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_load_board_search_locations
    ON load_legs (pickup_location_id, delivery_location_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_loads_search_equipment_commodity_visibility
    ON loads (organization_id, equipment_id, commodity_type_id, visibility, lifecycle_status)
    WHERE deleted_at IS NULL;
