-- Bulk load import and API posting ledger.

CREATE TABLE IF NOT EXISTS load_import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    requested_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    source_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(160) NULL,
    original_filename VARCHAR(255) NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    valid_rows INTEGER NOT NULL DEFAULT 0,
    invalid_rows INTEGER NOT NULL DEFAULT 0,
    created_load_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'previewed',
    error_export_csv TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_load_import_batches_idempotency
    ON load_import_batches (organization_id, source_type, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_load_import_batches_org_status
    ON load_import_batches (organization_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS load_import_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES load_import_batches(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    normalized_payload JSONB NULL,
    validation_status VARCHAR(32) NOT NULL,
    error_messages TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    load_id BIGINT NULL REFERENCES loads(id) ON DELETE SET NULL,
    idempotency_key VARCHAR(160) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_load_import_rows_batch
    ON load_import_rows (batch_id, row_number);

CREATE INDEX IF NOT EXISTS idx_load_import_rows_load
    ON load_import_rows (load_id)
    WHERE load_id IS NOT NULL;
