-- Rating, mileage, fuel, accessorials, and manual override audit.

CREATE TABLE IF NOT EXISTS mileage_calculation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    rule_name VARCHAR(160) NOT NULL,
    source_key VARCHAR(64) NOT NULL DEFAULT 'estimated_default',
    default_miles NUMERIC(12,2) NOT NULL DEFAULT 500,
    rate_per_mile NUMERIC(12,4) NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mileage_rules_org_active
    ON mileage_calculation_rules (organization_id, is_active, effective_from DESC);

CREATE TABLE IF NOT EXISTS fuel_surcharge_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    customer_contract_id BIGINT NULL REFERENCES customer_contracts(id) ON DELETE CASCADE,
    rule_name VARCHAR(160) NOT NULL,
    surcharge_type VARCHAR(32) NOT NULL DEFAULT 'percentage',
    surcharge_value NUMERIC(12,4) NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fuel_rules_org_contract_active
    ON fuel_surcharge_rules (organization_id, customer_contract_id, is_active, effective_from DESC);

CREATE TABLE IF NOT EXISTS accessorial_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    default_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    taxable BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

INSERT INTO accessorial_catalog (organization_id, code, label, default_amount, taxable)
SELECT org.id, item.code, item.label, item.default_amount, TRUE
FROM organizations org
CROSS JOIN (
    VALUES
        ('detention', 'Detention', 75.00),
        ('layover', 'Layover', 250.00),
        ('lumper', 'Lumper', 150.00),
        ('stop_off', 'Stop-off', 100.00),
        ('tonu', 'Truck ordered not used', 250.00),
        ('chassis', 'Chassis', 125.00),
        ('storage', 'Storage', 100.00),
        ('tolls', 'Tolls', 75.00),
        ('special_handling', 'Special handling', 150.00)
) AS item(code, label, default_amount)
ON CONFLICT (organization_id, code) DO NOTHING;

CREATE TABLE IF NOT EXISTS load_rating_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    load_id BIGINT NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
    leg_count INTEGER NOT NULL DEFAULT 0,
    base_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
    mileage_miles NUMERIC(12,2) NOT NULL DEFAULT 0,
    mileage_source VARCHAR(64) NOT NULL DEFAULT 'estimated_default',
    mileage_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
    fuel_surcharge NUMERIC(12,2) NOT NULL DEFAULT 0,
    accessorial_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_customer_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
    carrier_rate NUMERIC(12,2) NOT NULL DEFAULT 0,
    margin NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    explanation JSONB NOT NULL DEFAULT '[]'::jsonb,
    accessorial_breakdown JSONB NOT NULL DEFAULT '[]'::jsonb,
    manual_override_total NUMERIC(12,2) NULL,
    manual_override_reason TEXT NULL,
    calculated_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_load_rating_quotes_load_created
    ON load_rating_quotes (load_id, created_at DESC);

CREATE TABLE IF NOT EXISTS load_rate_override_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    load_id BIGINT NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
    quote_id BIGINT NOT NULL REFERENCES load_rating_quotes(id) ON DELETE CASCADE,
    previous_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    new_total NUMERIC(12,2) NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rate_override_audit_load
    ON load_rate_override_audit (load_id, created_at DESC);
