-- Address validation, normalized facilities, geocodes, and appointment workflow.

ALTER TABLE locations
    ADD COLUMN IF NOT EXISTS normalized_address TEXT NULL,
    ADD COLUMN IF NOT EXISTS google_place_id VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7) NULL,
    ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7) NULL,
    ADD COLUMN IF NOT EXISTS validation_status VARCHAR(32) NOT NULL DEFAULT 'manual',
    ADD COLUMN IF NOT EXISTS facility_type VARCHAR(64) NOT NULL DEFAULT 'customer_facility';

CREATE INDEX IF NOT EXISTS idx_locations_place_id
    ON locations (google_place_id)
    WHERE google_place_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_locations_geocode
    ON locations (latitude, longitude)
    WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE TABLE IF NOT EXISTS facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    facility_name VARCHAR(255) NOT NULL,
    facility_type VARCHAR(64) NOT NULL DEFAULT 'customer_facility',
    dock_instructions TEXT NULL,
    check_in_instructions TEXT NULL,
    parking_instructions TEXT NULL,
    lumper_instructions TEXT NULL,
    operating_hours JSONB NULL,
    contact_name VARCHAR(255) NULL,
    contact_phone VARCHAR(80) NULL,
    contact_email VARCHAR(255) NULL,
    warning_notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_facilities_org_type
    ON facilities (organization_id, facility_type);

CREATE TABLE IF NOT EXISTS facility_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    facility_id BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    note_type VARCHAR(64) NOT NULL DEFAULT 'operations',
    note TEXT NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'internal',
    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_facility_notes_facility
    ON facility_notes (facility_id, created_at DESC);

CREATE TABLE IF NOT EXISTS facility_appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    load_id BIGINT NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    facility_id BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    stop_type VARCHAR(32) NOT NULL,
    appointment_ref VARCHAR(160) NULL,
    appointment_start TIMESTAMP NOT NULL,
    appointment_end TIMESTAMP NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
    dock_name VARCHAR(120) NULL,
    contact_name VARCHAR(255) NULL,
    contact_phone VARCHAR(80) NULL,
    contact_email VARCHAR(255) NULL,
    notes TEXT NULL,
    scheduled_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_facility_appointments_load
    ON facility_appointments (load_id, appointment_start DESC);

CREATE INDEX IF NOT EXISTS idx_facility_appointments_leg
    ON facility_appointments (leg_id, stop_type, appointment_start DESC);

CREATE TABLE IF NOT EXISTS facility_appointment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL REFERENCES facility_appointments(id) ON DELETE CASCADE,
    event_type VARCHAR(64) NOT NULL,
    previous_start TIMESTAMP NULL,
    previous_end TIMESTAMP NULL,
    new_start TIMESTAMP NULL,
    new_end TIMESTAMP NULL,
    reason TEXT NULL,
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_facility_appointment_events_appointment
    ON facility_appointment_events (appointment_id, created_at DESC);
