-- Mode-specific workflow rules and validation events.

CREATE TABLE IF NOT EXISTS freight_mode_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode_key VARCHAR(64) NOT NULL UNIQUE,
    label VARCHAR(120) NOT NULL,
    support_status VARCHAR(32) NOT NULL DEFAULT 'supported',
    required_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    required_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
    validation_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO freight_mode_rules (
    mode_key, label, support_status, required_payload, required_documents, validation_message
)
VALUES
    (
        'FTL',
        'Full truckload',
        'supported',
        '{"required_fields":[]}'::jsonb,
        '["rate_confirmation","bill_of_lading"]'::jsonb,
        'FTL is supported with standard load, leg, facility, rating, and document workflow.'
    ),
    (
        'LTL',
        'Less-than-truckload',
        'supported',
        '{"one_of":["freight_class","nmfc","pieces","dimensions"]}'::jsonb,
        '["bill_of_lading","delivery_receipt"]'::jsonb,
        'LTL requires freight class, NMFC, pieces, or dimensions in mode details.'
    ),
    (
        'drayage',
        'Drayage',
        'supported',
        '{"one_of":["container_number","chassis_number","terminal","port","free_time_date"]}'::jsonb,
        '["delivery_order","interchange_receipt"]'::jsonb,
        'Drayage requires container, chassis, terminal, port, or free-time details.'
    ),
    (
        'intermodal',
        'Intermodal',
        'supported',
        '{"one_of":["container_number","rail_ramp","terminal","free_time_date"]}'::jsonb,
        '["interchange_receipt","bill_of_lading"]'::jsonb,
        'Intermodal requires container, ramp, terminal, or free-time details.'
    ),
    (
        'cross_border',
        'Cross-border',
        'deferred',
        '{"one_of":["customs_broker","border_crossing","pars","paps","customs_document"]}'::jsonb,
        '["customs_invoice","pars_paps","broker_packet"]'::jsonb,
        'Cross-border workflow is deferred until tax, FX, duties, customs, and localization controls are complete.'
    ),
    (
        'freight_forwarding',
        'Freight forwarding',
        'deferred',
        '{"one_of":["forwarder_reference","incoterms","house_bill","master_bill"]}'::jsonb,
        '["house_bill","master_bill","commercial_invoice"]'::jsonb,
        'Freight forwarding workflow is deferred until legal operating model and forwarding controls are complete.'
    ),
    (
        'mixed_mode',
        'Mixed mode',
        'deferred',
        '{"one_of":["mode_segments","handoff_points"]}'::jsonb,
        '["mode_plan"]'::jsonb,
        'Mixed-mode workflow is deferred until segment-level statuses, documents, and rating are implemented.'
    )
ON CONFLICT (mode_key) DO UPDATE SET
    label = EXCLUDED.label,
    support_status = EXCLUDED.support_status,
    required_payload = EXCLUDED.required_payload,
    required_documents = EXCLUDED.required_documents,
    validation_message = EXCLUDED.validation_message,
    updated_at = CURRENT_TIMESTAMP;

ALTER TABLE loads
    ADD COLUMN IF NOT EXISTS mode_validation_status VARCHAR(32) NOT NULL DEFAULT 'validated',
    ADD COLUMN IF NOT EXISTS mode_validation_notes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

CREATE TABLE IF NOT EXISTS load_mode_validation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id BIGINT NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
    mode_key VARCHAR(64) NOT NULL,
    validation_status VARCHAR(32) NOT NULL,
    validation_notes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_load_mode_validation_events_load
    ON load_mode_validation_events (load_id, created_at DESC);
