-- Time zone, unit, currency, and localization rules.

CREATE TABLE IF NOT EXISTS organization_localization_settings (
    organization_id BIGINT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    locale VARCHAR(32) NOT NULL DEFAULT 'en-US',
    time_zone VARCHAR(80) NOT NULL DEFAULT 'UTC',
    distance_unit VARCHAR(16) NOT NULL DEFAULT 'mi',
    weight_unit VARCHAR(16) NOT NULL DEFAULT 'LBS',
    dimension_unit VARCHAR(16) NOT NULL DEFAULT 'in',
    temperature_unit VARCHAR(16) NOT NULL DEFAULT 'F',
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO organization_localization_settings (
    organization_id, locale, time_zone, distance_unit, weight_unit,
    dimension_unit, temperature_unit, currency
)
SELECT id, 'en-US', 'UTC', 'mi', 'LBS', 'in', 'F', 'USD'
FROM organizations
ON CONFLICT (organization_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS load_localization_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    load_id BIGINT NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
    locale VARCHAR(32) NOT NULL,
    time_zone VARCHAR(80) NOT NULL,
    canonical_distance_unit VARCHAR(16) NOT NULL DEFAULT 'mi',
    display_distance_unit VARCHAR(16) NOT NULL,
    canonical_weight_unit VARCHAR(16) NOT NULL DEFAULT 'LBS',
    display_weight_unit VARCHAR(16) NOT NULL,
    canonical_weight_lbs NUMERIC(14,4) NULL,
    display_weight NUMERIC(14,4) NULL,
    dimension_unit VARCHAR(16) NOT NULL,
    temperature_unit VARCHAR(16) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    validation_notes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_load_localization_snapshots_load
    ON load_localization_snapshots (load_id, created_at DESC);

ALTER TABLE facility_appointments
    ADD COLUMN IF NOT EXISTS time_zone VARCHAR(80) NOT NULL DEFAULT 'UTC';

ALTER TABLE facility_appointment_events
    ADD COLUMN IF NOT EXISTS time_zone VARCHAR(80) NULL;
