-- Cross-border tax, FX, duties, and Incoterms governance.

CREATE TABLE IF NOT EXISTS cross_border_finance_policies (
    organization_id BIGINT PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    operating_region VARCHAR(64) NOT NULL DEFAULT 'US_DOMESTIC',
    multi_currency_rating_supported BOOLEAN NOT NULL DEFAULT FALSE,
    multi_currency_invoicing_supported BOOLEAN NOT NULL DEFAULT FALSE,
    multi_currency_settlement_supported BOOLEAN NOT NULL DEFAULT FALSE,
    supported_currencies TEXT[] NOT NULL DEFAULT ARRAY['USD']::TEXT[],
    fx_rate_source VARCHAR(160) NULL,
    fx_rate_lock_timing VARCHAR(160) NULL,
    fx_rounding_rule VARCHAR(160) NULL,
    tax_policy_status VARCHAR(32) NOT NULL DEFAULT 'deferred',
    duty_policy_status VARCHAR(32) NOT NULL DEFAULT 'deferred',
    customs_fee_policy_status VARCHAR(32) NOT NULL DEFAULT 'deferred',
    incoterms_supported BOOLEAN NOT NULL DEFAULT FALSE,
    unsupported_message TEXT NOT NULL DEFAULT 'Cross-border financial obligations, non-USD rating, non-USD invoicing, non-USD settlement, duties, VAT/GST, customs fees, and Incoterms are deferred for the first enterprise release until Legal and Finance approve the operating model.',
    approved_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO cross_border_finance_policies (
    organization_id,
    operating_region,
    multi_currency_rating_supported,
    multi_currency_invoicing_supported,
    multi_currency_settlement_supported,
    supported_currencies,
    tax_policy_status,
    duty_policy_status,
    customs_fee_policy_status,
    incoterms_supported
)
SELECT
    id,
    'US_DOMESTIC',
    FALSE,
    FALSE,
    FALSE,
    ARRAY['USD']::TEXT[],
    'deferred',
    'deferred',
    'deferred',
    FALSE
FROM organizations
ON CONFLICT (organization_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS load_cross_border_finance_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    load_id BIGINT NULL REFERENCES loads(id) ON DELETE CASCADE,
    check_context VARCHAR(64) NOT NULL,
    freight_mode VARCHAR(32) NULL,
    requested_currency VARCHAR(8) NULL,
    support_status VARCHAR(32) NOT NULL DEFAULT 'blocked',
    decision_message TEXT NOT NULL,
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_load_cross_border_finance_checks_load
    ON load_cross_border_finance_checks (load_id, created_at DESC);
