-- Governed master data and configuration administration.

CREATE TABLE IF NOT EXISTS service_level_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    description TEXT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS rejection_reason_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    description TEXT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS exception_reason_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    description TEXT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS governed_configuration_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    config_area VARCHAR(80) NOT NULL,
    target_table VARCHAR(80) NOT NULL,
    target_record_id BIGINT NULL,
    change_type VARCHAR(32) NOT NULL,
    requested_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    approved_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    approval_status VARCHAR(32) NOT NULL DEFAULT 'approved',
    rollback_payload JSONB NULL,
    change_summary TEXT NOT NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_governed_configuration_changes_org_area
    ON governed_configuration_changes (organization_id, config_area, created_at DESC);

INSERT INTO service_level_catalog (organization_id, code, label, description, requires_approval)
SELECT org.id, item.code, item.label, item.description, item.requires_approval
FROM organizations org
CROSS JOIN (
    VALUES
        ('standard', 'Standard', 'Default transit expectation with normal appointment handling.', FALSE),
        ('expedited', 'Expedited', 'Time-sensitive freight requiring dispatch review.', TRUE),
        ('guaranteed', 'Guaranteed', 'Guaranteed service commitment requiring customer approval.', TRUE),
        ('team', 'Team', 'Team-driver or equivalent service expectation.', TRUE)
) AS item(code, label, description, requires_approval)
ON CONFLICT (organization_id, code) DO NOTHING;

INSERT INTO rejection_reason_catalog (organization_id, code, label, description, requires_approval)
SELECT org.id, item.code, item.label, item.description, item.requires_approval
FROM organizations org
CROSS JOIN (
    VALUES
        ('capacity_unavailable', 'Capacity unavailable', 'Carrier or marketplace capacity is unavailable.', FALSE),
        ('compliance_block', 'Compliance block', 'Carrier, driver, document, or equipment compliance blocks the move.', TRUE),
        ('rate_rejected', 'Rate rejected', 'Offered rate does not meet commercial rules.', FALSE),
        ('customer_cancelled', 'Customer cancelled', 'Customer cancelled or withdrew the freight.', TRUE)
) AS item(code, label, description, requires_approval)
ON CONFLICT (organization_id, code) DO NOTHING;

INSERT INTO exception_reason_catalog (organization_id, code, label, description, requires_approval)
SELECT org.id, item.code, item.label, item.description, item.requires_approval
FROM organizations org
CROSS JOIN (
    VALUES
        ('late_pickup', 'Late pickup', 'Pickup appointment or pickup milestone is late.', FALSE),
        ('late_delivery', 'Late delivery', 'Delivery appointment or delivery milestone is late.', FALSE),
        ('missing_pod', 'Missing POD', 'Proof of delivery is missing after delivery.', TRUE),
        ('payment_hold', 'Payment hold', 'Finance hold blocks release or settlement.', TRUE),
        ('tms_drift', 'TMS drift', 'External TMS status or rate has drifted from STLoads.', TRUE)
) AS item(code, label, description, requires_approval)
ON CONFLICT (organization_id, code) DO NOTHING;
