-- Additional governed operational catalogs for enterprise configuration.

CREATE TABLE IF NOT EXISTS trailer_type_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    description TEXT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS hazmat_class_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    code VARCHAR(64) NOT NULL,
    label VARCHAR(160) NOT NULL,
    description TEXT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

ALTER TABLE accessorial_catalog
    ADD COLUMN IF NOT EXISTS description TEXT NULL,
    ADD COLUMN IF NOT EXISTS requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN IF NOT EXISTS effective_to DATE NULL;

INSERT INTO trailer_type_catalog (organization_id, code, label, description, requires_approval)
SELECT org.id, item.code, item.label, item.description, item.requires_approval
FROM organizations org
CROSS JOIN (
    VALUES
        ('dry_van_53', '53 ft Dry Van', 'Standard enclosed 53 ft dry van trailer.', FALSE),
        ('reefer_53', '53 ft Reefer', 'Temperature-controlled refrigerated trailer.', TRUE),
        ('flatbed_48', '48 ft Flatbed', 'Open-deck flatbed trailer for securement-controlled freight.', TRUE),
        ('step_deck', 'Step Deck', 'Step-deck trailer for taller open-deck freight.', TRUE),
        ('container_chassis', 'Container Chassis', 'Chassis for drayage and intermodal container moves.', TRUE)
) AS item(code, label, description, requires_approval)
ON CONFLICT (organization_id, code) DO NOTHING;

INSERT INTO hazmat_class_catalog (organization_id, code, label, description, requires_approval)
SELECT org.id, item.code, item.label, item.description, TRUE
FROM organizations org
CROSS JOIN (
    VALUES
        ('class_1', 'Class 1 Explosives', 'Explosive materials; always requires explicit approval and compliance checks.'),
        ('class_2', 'Class 2 Gases', 'Compressed, liquefied, or dissolved gases.'),
        ('class_3', 'Class 3 Flammable Liquids', 'Flammable liquids subject to hazmat handling.'),
        ('class_8', 'Class 8 Corrosives', 'Corrosive materials requiring restricted handling.')
) AS item(code, label, description)
ON CONFLICT (organization_id, code) DO NOTHING;
