-- Customer-specific governed configuration rules.

CREATE TABLE IF NOT EXISTS customer_configuration_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    config_key VARCHAR(96) NOT NULL,
    config_area VARCHAR(64) NOT NULL,
    customer_contract_id BIGINT NULL REFERENCES customer_contracts(id) ON DELETE CASCADE,
    customer_contract_lane_id BIGINT NULL REFERENCES customer_contract_lanes(id) ON DELETE CASCADE,
    facility_id BIGINT NULL REFERENCES facilities(id) ON DELETE SET NULL,
    carrier_group_key VARCHAR(96) NULL,
    visibility_rule JSONB NOT NULL DEFAULT '{}'::jsonb,
    compliance_gate JSONB NOT NULL DEFAULT '{}'::jsonb,
    billing_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    notification_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    required_reference_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, config_key)
);

CREATE INDEX IF NOT EXISTS idx_customer_configuration_rules_org_area
    ON customer_configuration_rules (organization_id, config_area, is_active, effective_from DESC);

CREATE INDEX IF NOT EXISTS idx_customer_configuration_rules_contract_lane
    ON customer_configuration_rules (customer_contract_id, customer_contract_lane_id)
    WHERE is_active = TRUE;
