CREATE TABLE IF NOT EXISTS carrier_capacity_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    carrier_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    equipment_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    lane_preferences TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    operating_regions TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    preferred_commodities TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    service_levels TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    certifications TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    availability_status VARCHAR(32) NOT NULL DEFAULT 'available',
    available_power_units INT NOT NULL DEFAULT 0,
    insurance_limit_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
    capacity_notes TEXT NULL,
    last_updated_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (carrier_user_id),
    CONSTRAINT chk_carrier_capacity_availability
        CHECK (availability_status IN ('available', 'limited', 'unavailable', 'seasonal', 'paused')),
    CONSTRAINT chk_carrier_capacity_power_units CHECK (available_power_units >= 0),
    CONSTRAINT chk_carrier_capacity_insurance_limit CHECK (insurance_limit_usd >= 0)
);

CREATE INDEX IF NOT EXISTS idx_carrier_capacity_org_availability
    ON carrier_capacity_profiles (organization_id, availability_status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_carrier_capacity_equipment
    ON carrier_capacity_profiles USING GIN (equipment_types);

CREATE INDEX IF NOT EXISTS idx_carrier_capacity_regions
    ON carrier_capacity_profiles USING GIN (operating_regions);
