CREATE TABLE IF NOT EXISTS carrier_network_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    carrier_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    relationship_status VARCHAR(32) NOT NULL DEFAULT 'approved',
    carrier_group_key VARCHAR(96) NULL,
    notes TEXT NULL,
    effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
    effective_to DATE NULL,
    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_user_id, carrier_user_id),
    CONSTRAINT chk_carrier_network_status
        CHECK (relationship_status IN ('approved', 'preferred', 'backup', 'blocked'))
);

CREATE INDEX IF NOT EXISTS idx_carrier_network_owner_status
    ON carrier_network_memberships (owner_user_id, relationship_status, effective_from DESC);

CREATE INDEX IF NOT EXISTS idx_carrier_network_carrier_status
    ON carrier_network_memberships (carrier_user_id, relationship_status, effective_from DESC);

CREATE INDEX IF NOT EXISTS idx_carrier_network_group
    ON carrier_network_memberships (organization_id, carrier_group_key)
    WHERE carrier_group_key IS NOT NULL;
