CREATE TABLE IF NOT EXISTS booking_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_user_id BIGINT NOT NULL,
    load_leg_id BIGINT NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_idempotency_carrier_user_id FOREIGN KEY (carrier_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_idempotency_load_leg_id FOREIGN KEY (load_leg_id) REFERENCES load_legs(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_idempotency_carrier_key
    ON booking_idempotency_keys (carrier_user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_booking_idempotency_load_leg_id
    ON booking_idempotency_keys (load_leg_id);
