CREATE TABLE IF NOT EXISTS dispatch_work_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    desk_key VARCHAR(40) NOT NULL,
    assigned_user_id BIGINT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    sla_due_at TIMESTAMP(6) NULL,
    escalation_reason TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dispatch_work_items_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_work_items_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_dispatch_work_items_priority CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    CONSTRAINT chk_dispatch_work_items_status CHECK (status IN ('open', 'in_progress', 'escalated', 'resolved', 'closed'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dispatch_work_items_leg_desk
    ON dispatch_work_items (leg_id, desk_key);

CREATE INDEX IF NOT EXISTS idx_dispatch_work_items_assigned_user_id
    ON dispatch_work_items (assigned_user_id);

CREATE INDEX IF NOT EXISTS idx_dispatch_work_items_sla_due_at
    ON dispatch_work_items (sla_due_at);

CREATE TABLE IF NOT EXISTS dispatch_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    load_id BIGINT NOT NULL,
    desk_key VARCHAR(40) NOT NULL,
    visibility VARCHAR(30) NOT NULL DEFAULT 'internal',
    note TEXT NOT NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dispatch_notes_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_notes_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_notes_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_dispatch_notes_visibility CHECK (visibility IN ('internal', 'customer_visible'))
);

CREATE INDEX IF NOT EXISTS idx_dispatch_notes_leg_desk_created
    ON dispatch_notes (leg_id, desk_key, created_at DESC);

CREATE TABLE IF NOT EXISTS dispatch_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL,
    load_id BIGINT NOT NULL,
    desk_key VARCHAR(40) NOT NULL,
    exception_type VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    severity VARCHAR(20) NOT NULL DEFAULT 'medium',
    detected_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP(6) NULL,
    resolution_note TEXT NULL,
    resolved_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dispatch_exceptions_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_exceptions_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_dispatch_exceptions_resolved_by_user_id FOREIGN KEY (resolved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_dispatch_exceptions_status CHECK (status IN ('open', 'in_progress', 'resolved', 'dismissed')),
    CONSTRAINT chk_dispatch_exceptions_severity CHECK (severity IN ('low', 'medium', 'high', 'critical'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_dispatch_exceptions_open_type
    ON dispatch_exceptions (leg_id, exception_type)
    WHERE status IN ('open', 'in_progress');

CREATE INDEX IF NOT EXISTS idx_dispatch_exceptions_desk_status
    ON dispatch_exceptions (desk_key, status);
