-- Phase 8 execution privacy, mobile capture, and risk scaffolding.

CREATE TABLE IF NOT EXISTS execution_tracking_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    consent_text TEXT NOT NULL,
    consented_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMP NULL,
    retention_days INT NOT NULL DEFAULT 90,
    customer_visible_scope VARCHAR(80) NOT NULL DEFAULT 'latest_location_and_status',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_execution_tracking_consents_active
    ON execution_tracking_consents (leg_id, user_id)
    WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_execution_tracking_consents_leg
    ON execution_tracking_consents (leg_id, consented_at DESC);

CREATE TABLE IF NOT EXISTS execution_offline_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    submission_type VARCHAR(64) NOT NULL,
    client_submission_id VARCHAR(160) NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMP NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP NULL,
    processing_status VARCHAR(32) NOT NULL DEFAULT 'received',
    reconciliation_note TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_execution_offline_submission_client
    ON execution_offline_submissions (leg_id, user_id, client_submission_id)
    WHERE client_submission_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_execution_offline_submissions_leg
    ON execution_offline_submissions (leg_id, processing_status, received_at DESC);

CREATE TABLE IF NOT EXISTS execution_risk_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    risk_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'info',
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    signal TEXT NOT NULL,
    detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_execution_risk_events_leg
    ON execution_risk_events (leg_id, status, detected_at DESC);
