-- Phase 8 closeout, customer visibility, claims/accessorials, telematics, and route planning.

CREATE TABLE IF NOT EXISTS execution_closeout_packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    pod_review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    required_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
    approved_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMP NULL,
    export_path VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_execution_closeout_packages_leg
    ON execution_closeout_packages (leg_id);

CREATE TABLE IF NOT EXISTS execution_customer_tracking_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    share_token VARCHAR(128) NOT NULL,
    visibility_scope VARCHAR(80) NOT NULL DEFAULT 'status_eta_latest_location',
    expires_at TIMESTAMP NOT NULL,
    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_execution_customer_tracking_links_token
    ON execution_customer_tracking_links (share_token);

CREATE INDEX IF NOT EXISTS idx_execution_customer_tracking_links_leg
    ON execution_customer_tracking_links (leg_id, expires_at DESC);

CREATE TABLE IF NOT EXISTS execution_finance_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    exception_type VARCHAR(64) NOT NULL,
    amount_cents BIGINT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    visibility VARCHAR(32) NOT NULL DEFAULT 'internal',
    description TEXT NOT NULL,
    evidence_document_id BIGINT NULL REFERENCES leg_documents(id) ON DELETE SET NULL,
    created_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    resolved_by_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    resolved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_execution_finance_exceptions_leg
    ON execution_finance_exceptions (leg_id, status, exception_type);

CREATE TABLE IF NOT EXISTS telematics_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    carrier_user_id BIGINT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider_key VARCHAR(80) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'planned',
    consent_required BOOLEAN NOT NULL DEFAULT TRUE,
    last_ping_at TIMESTAMP NULL,
    fallback_behavior TEXT NOT NULL DEFAULT 'Use mobile driver tracking when provider data is stale or unavailable.',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_telematics_connections_carrier_provider
    ON telematics_connections (carrier_user_id, provider_key)
    WHERE carrier_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_telematics_connections_carrier
    ON telematics_connections (carrier_user_id, provider_key, status);

CREATE TABLE IF NOT EXISTS execution_route_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leg_id BIGINT NOT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    provider_key VARCHAR(80) NOT NULL DEFAULT 'manual',
    distance_miles NUMERIC(10,2) NULL,
    duration_minutes INT NULL,
    truck_safe BOOLEAN NOT NULL DEFAULT FALSE,
    constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'planned',
    calculated_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_execution_route_plans_leg
    ON execution_route_plans (leg_id);
