-- Phase 9 payment idempotency for escrow and Stripe money movement.

CREATE TABLE IF NOT EXISTS payment_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(160) NOT NULL,
    flow VARCHAR(64) NOT NULL,
    leg_id BIGINT NULL REFERENCES load_legs(id) ON DELETE CASCADE,
    actor_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
    request_fingerprint VARCHAR(128) NOT NULL,
    response_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_idempotency_keys_scope
    ON payment_idempotency_keys (flow, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_payment_idempotency_keys_leg
    ON payment_idempotency_keys (leg_id, flow, created_at DESC);
