-- Phase 9 Stripe webhook de-duplication.

CREATE TABLE IF NOT EXISTS payment_stripe_webhook_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_event_id VARCHAR(191) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payment_intent_id VARCHAR(191) NULL,
    stripe_account_id VARCHAR(191) NULL,
    processing_status VARCHAR(32) NOT NULL DEFAULT 'processing',
    response_json JSONB NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_stripe_webhook_events_event_id
    ON payment_stripe_webhook_events (stripe_event_id);

CREATE INDEX IF NOT EXISTS idx_payment_stripe_webhook_events_type_created
    ON payment_stripe_webhook_events (event_type, created_at DESC);
