-- Finance-grade payment ledger for escrow money movement.

CREATE TABLE IF NOT EXISTS payment_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_key VARCHAR(191) NOT NULL,
    entry_type VARCHAR(64) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    amount_cents BIGINT NOT NULL,
    platform_fee_cents BIGINT NOT NULL DEFAULT 0,
    load_id BIGINT NULL,
    leg_id BIGINT NULL,
    escrow_id BIGINT NULL,
    payer_user_id BIGINT NULL,
    payee_user_id BIGINT NULL,
    actor_user_id BIGINT NULL,
    audit_event_id BIGINT NULL,
    transfer_group VARCHAR(191) NULL,
    payment_intent_id VARCHAR(191) NULL,
    charge_id VARCHAR(191) NULL,
    transfer_id VARCHAR(191) NULL,
    stripe_refund_id VARCHAR(191) NULL,
    stripe_dispute_id VARCHAR(191) NULL,
    adjustment_reference VARCHAR(191) NULL,
    description TEXT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_ledger_source_event_key UNIQUE (source_event_key),
    CONSTRAINT chk_payment_ledger_direction CHECK (direction IN ('debit', 'credit', 'hold', 'release', 'info')),
    CONSTRAINT fk_payment_ledger_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_escrow_id FOREIGN KEY (escrow_id) REFERENCES escrows(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_payer_user_id FOREIGN KEY (payer_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_payee_user_id FOREIGN KEY (payee_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_payment_ledger_audit_event_id FOREIGN KEY (audit_event_id) REFERENCES audit_events(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_payment_ledger_leg_created_at ON payment_ledger_entries (leg_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_load_created_at ON payment_ledger_entries (load_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_escrow_created_at ON payment_ledger_entries (escrow_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_entry_type_created_at ON payment_ledger_entries (entry_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_ledger_payment_intent_id ON payment_ledger_entries (payment_intent_id) WHERE payment_intent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_ledger_transfer_id ON payment_ledger_entries (transfer_id) WHERE transfer_id IS NOT NULL;
