-- Finance approval workflow for high-risk payment actions.

CREATE TABLE IF NOT EXISTS finance_approval_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approval_type VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id BIGINT NOT NULL,
    organization_id BIGINT NULL,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    required_approval_count INT NOT NULL DEFAULT 1,
    requested_by_user_id BIGINT NULL,
    first_approved_by_user_id BIGINT NULL,
    second_approved_by_user_id BIGINT NULL,
    rejected_by_user_id BIGINT NULL,
    reason TEXT NULL,
    decision_note TEXT NULL,
    requested_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    first_approved_at TIMESTAMP(6) NULL,
    second_approved_at TIMESTAMP(6) NULL,
    rejected_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_finance_approval_status CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    CONSTRAINT fk_finance_approval_organization_id FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_approval_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_approval_first_by FOREIGN KEY (first_approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_approval_second_by FOREIGN KEY (second_approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_finance_approval_rejected_by FOREIGN KEY (rejected_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_finance_approval_open_entity
    ON finance_approval_requests (approval_type, entity_type, entity_id)
    WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_finance_approval_status_updated_at
    ON finance_approval_requests (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_finance_approval_org_status
    ON finance_approval_requests (organization_id, status, updated_at DESC);
