-- Customer invoices and carrier settlements derived from released escrow.

CREATE TABLE IF NOT EXISTS customer_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(64) NOT NULL,
    load_id BIGINT NOT NULL,
    leg_id BIGINT NOT NULL,
    customer_user_id BIGINT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    freight_amount_cents BIGINT NOT NULL DEFAULT 0,
    accessorial_amount_cents BIGINT NOT NULL DEFAULT 0,
    tax_amount_cents BIGINT NOT NULL DEFAULT 0,
    adjustment_amount_cents BIGINT NOT NULL DEFAULT 0,
    total_amount_cents BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    payment_terms_days INT NOT NULL DEFAULT 30,
    issued_at TIMESTAMP(6) NULL,
    due_at TIMESTAMP(6) NULL,
    paid_at TIMESTAMP(6) NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customer_invoices_invoice_number UNIQUE (invoice_number),
    CONSTRAINT uq_customer_invoices_leg_id UNIQUE (leg_id),
    CONSTRAINT chk_customer_invoice_status CHECK (status IN ('draft', 'issued', 'partially_paid', 'paid', 'void')),
    CONSTRAINT fk_customer_invoices_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_invoices_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_invoices_customer_user_id FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_customer_invoices_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS customer_invoice_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL,
    line_type VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_amount_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_customer_invoice_lines_type UNIQUE (invoice_id, line_type),
    CONSTRAINT fk_customer_invoice_lines_invoice_id FOREIGN KEY (invoice_id) REFERENCES customer_invoices(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS carrier_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_number VARCHAR(64) NOT NULL,
    load_id BIGINT NOT NULL,
    leg_id BIGINT NOT NULL,
    carrier_user_id BIGINT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    gross_amount_cents BIGINT NOT NULL DEFAULT 0,
    platform_fee_cents BIGINT NOT NULL DEFAULT 0,
    accessorial_amount_cents BIGINT NOT NULL DEFAULT 0,
    tax_withholding_cents BIGINT NOT NULL DEFAULT 0,
    adjustment_amount_cents BIGINT NOT NULL DEFAULT 0,
    net_amount_cents BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    payment_terms_days INT NOT NULL DEFAULT 0,
    approved_at TIMESTAMP(6) NULL,
    released_at TIMESTAMP(6) NULL,
    paid_at TIMESTAMP(6) NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_carrier_settlements_settlement_number UNIQUE (settlement_number),
    CONSTRAINT uq_carrier_settlements_leg_id UNIQUE (leg_id),
    CONSTRAINT chk_carrier_settlement_status CHECK (status IN ('pending', 'approved', 'released', 'paid', 'void')),
    CONSTRAINT fk_carrier_settlements_load_id FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_settlements_leg_id FOREIGN KEY (leg_id) REFERENCES load_legs(id) ON DELETE CASCADE,
    CONSTRAINT fk_carrier_settlements_carrier_user_id FOREIGN KEY (carrier_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_carrier_settlements_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS carrier_settlement_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_id BIGINT NOT NULL,
    line_type VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1,
    unit_amount_cents BIGINT NOT NULL DEFAULT 0,
    amount_cents BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_carrier_settlement_lines_type UNIQUE (settlement_id, line_type),
    CONSTRAINT fk_carrier_settlement_lines_settlement_id FOREIGN KEY (settlement_id) REFERENCES carrier_settlements(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_customer_invoices_status_due_at ON customer_invoices (status, due_at);
CREATE INDEX IF NOT EXISTS idx_customer_invoices_customer_status ON customer_invoices (customer_user_id, status);
CREATE INDEX IF NOT EXISTS idx_carrier_settlements_status_created_at ON carrier_settlements (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_carrier_settlements_carrier_status ON carrier_settlements (carrier_user_id, status);
