-- Platform billing, shipper credit controls, and payout destination review controls.

CREATE TABLE IF NOT EXISTS stloads_subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_key VARCHAR(64) NOT NULL,
    plan_name VARCHAR(128) NOT NULL,
    billing_model VARCHAR(64) NOT NULL DEFAULT 'hybrid',
    monthly_base_cents BIGINT NOT NULL DEFAULT 0,
    per_load_cents BIGINT NOT NULL DEFAULT 0,
    per_api_call_cents BIGINT NOT NULL DEFAULT 0,
    seat_included_count INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stloads_subscription_plans_key UNIQUE (plan_key)
);

CREATE TABLE IF NOT EXISTS stloads_billing_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NULL,
    customer_user_id BIGINT NULL,
    plan_id BIGINT NULL,
    billing_email VARCHAR(255) NULL,
    billing_status VARCHAR(32) NOT NULL DEFAULT 'active',
    payment_method_status VARCHAR(32) NOT NULL DEFAULT 'not_configured',
    current_period_start TIMESTAMP(6) NULL,
    current_period_end TIMESTAMP(6) NULL,
    cancelled_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_stloads_billing_status CHECK (billing_status IN ('active', 'trialing', 'past_due', 'cancelled', 'suspended')),
    CONSTRAINT fk_stloads_billing_accounts_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_stloads_billing_accounts_user FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_stloads_billing_accounts_plan FOREIGN KEY (plan_id) REFERENCES stloads_subscription_plans(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS stloads_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_account_id BIGINT NULL,
    organization_id BIGINT NULL,
    event_type VARCHAR(64) NOT NULL,
    quantity BIGINT NOT NULL DEFAULT 1,
    source_reference VARCHAR(191) NULL,
    occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stloads_usage_events_account FOREIGN KEY (billing_account_id) REFERENCES stloads_billing_accounts(id) ON DELETE SET NULL,
    CONSTRAINT fk_stloads_usage_events_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shipper_credit_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NULL,
    customer_user_id BIGINT NULL,
    credit_status VARCHAR(32) NOT NULL DEFAULT 'normal',
    credit_limit_cents BIGINT NOT NULL DEFAULT 0,
    open_ar_cents BIGINT NOT NULL DEFAULT 0,
    overdue_ar_cents BIGINT NOT NULL DEFAULT 0,
    payment_terms_days INT NOT NULL DEFAULT 30,
    credit_hold BOOLEAN NOT NULL DEFAULT FALSE,
    override_required BOOLEAN NOT NULL DEFAULT FALSE,
    internal_risk_note TEXT NULL,
    updated_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_shipper_credit_status CHECK (credit_status IN ('normal', 'watch', 'over_limit', 'hold', 'collections')),
    CONSTRAINT fk_shipper_credit_accounts_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
    CONSTRAINT fk_shipper_credit_accounts_user FOREIGN KEY (customer_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_shipper_credit_accounts_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_shipper_credit_accounts_org_customer
    ON shipper_credit_accounts (organization_id, customer_user_id);

CREATE TABLE IF NOT EXISTS ar_collection_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_account_id BIGINT NOT NULL,
    invoice_id BIGINT NULL,
    note_type VARCHAR(64) NOT NULL DEFAULT 'collection_note',
    promise_to_pay_at TIMESTAMP(6) NULL,
    note TEXT NOT NULL,
    created_by_user_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ar_collection_notes_credit_account FOREIGN KEY (credit_account_id) REFERENCES shipper_credit_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_ar_collection_notes_invoice FOREIGN KEY (invoice_id) REFERENCES customer_invoices(id) ON DELETE SET NULL,
    CONSTRAINT fk_ar_collection_notes_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payout_destination_change_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_user_id BIGINT NOT NULL,
    stripe_connect_account_id VARCHAR(191) NULL,
    change_type VARCHAR(64) NOT NULL DEFAULT 'payout_destination_change',
    risk_status VARCHAR(32) NOT NULL DEFAULT 'review_required',
    cooling_off_until TIMESTAMP(6) NULL,
    requested_by_user_id BIGINT NULL,
    reviewed_by_user_id BIGINT NULL,
    review_note TEXT NULL,
    notification_sent_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_payout_destination_risk_status CHECK (risk_status IN ('review_required', 'cooling_off', 'approved', 'rejected', 'blocked')),
    CONSTRAINT fk_payout_destination_carrier FOREIGN KEY (carrier_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_payout_destination_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_payout_destination_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_stloads_usage_events_org_type_time ON stloads_usage_events (organization_id, event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_shipper_credit_accounts_status ON shipper_credit_accounts (credit_status, credit_hold);
CREATE INDEX IF NOT EXISTS idx_ar_collection_notes_promise ON ar_collection_notes (promise_to_pay_at) WHERE promise_to_pay_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payout_destination_reviews_status ON payout_destination_change_reviews (risk_status, created_at DESC);
