-- Phase 9 completion: platform billing invoices, credit overrides, and payout review workflow.

CREATE TABLE IF NOT EXISTS stloads_platform_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_account_id BIGINT NOT NULL,
    organization_id BIGINT NULL,
    invoice_number VARCHAR(64) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    base_amount_cents BIGINT NOT NULL DEFAULT 0,
    usage_amount_cents BIGINT NOT NULL DEFAULT 0,
    total_amount_cents BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'issued',
    issued_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '30 days',
    paid_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_stloads_platform_invoices_number UNIQUE (invoice_number),
    CONSTRAINT chk_stloads_platform_invoice_status CHECK (status IN ('issued', 'paid', 'void', 'past_due')),
    CONSTRAINT fk_stloads_platform_invoices_account FOREIGN KEY (billing_account_id) REFERENCES stloads_billing_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_stloads_platform_invoices_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shipper_credit_override_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_account_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NULL,
    approved_by_user_id BIGINT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    reason TEXT NOT NULL,
    expires_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_shipper_credit_override_status CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
    CONSTRAINT fk_shipper_credit_override_account FOREIGN KEY (credit_account_id) REFERENCES shipper_credit_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_shipper_credit_override_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_shipper_credit_override_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_stloads_platform_invoices_account_status ON stloads_platform_invoices (billing_account_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_stloads_platform_invoices_org_status ON stloads_platform_invoices (organization_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_shipper_credit_override_status ON shipper_credit_override_requests (status, created_at DESC);
